/* =========================================================
   MariaDB DDL - External Supplier DB
   Converted from Oracle 21c DDL
========================================================= */

SET FOREIGN_KEY_CHECKS = 0;

DROP TRIGGER IF EXISTS TRG_SUPPLIER_UPD_AT;
DROP TRIGGER IF EXISTS TRG_SUP_PRODUCT_UPD_AT;
DROP TRIGGER IF EXISTS TRG_SUP_INV_UPD_AT;
DROP TRIGGER IF EXISTS TRG_EXT_ORDER_UPD_AT;
DROP TRIGGER IF EXISTS TRG_EXT_SHIPMENT_UPD_AT;
DROP TRIGGER IF EXISTS TRG_EXT_SHIPMENT_AI;

DROP TABLE IF EXISTS EXTERNAL_SHIPMENT;
DROP TABLE IF EXISTS EXTERNAL_ORDER_RECEIPT;
DROP TABLE IF EXISTS SUPPLIER_INVENTORY;
DROP TABLE IF EXISTS SUPPLIER_PRODUCT;
DROP TABLE IF EXISTS SUPPLIER;

SET FOREIGN_KEY_CHECKS = 1;

/* =========================================================
   1. SUPPLIER - 발주처
========================================================= */
CREATE TABLE SUPPLIER
(
    SUPPLIER_ID      BIGINT AUTO_INCREMENT                 NOT NULL COMMENT '발주처 고유 번호',
    SUPPLIER_NAME    VARCHAR(100)                          NOT NULL COMMENT '발주처명',
    SUPPLIER_TYPE    VARCHAR(50)                           NOT NULL COMMENT '발주처 유형',
    ADDRESS          VARCHAR(300) COMMENT '발주처 주소',
    PHONE_NUMBER     VARCHAR(30) COMMENT '발주처 연락처',
    OPERATION_STATUS VARCHAR(20) DEFAULT 'ACTIVE'          NOT NULL COMMENT '발주처 운영 상태: ACTIVE, INACTIVE, CLOSED',
    CREATED_AT       DATETIME    DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '발주처 정보 등록 일시',
    UPDATED_AT       DATETIME                              NULL COMMENT '발주처 정보 최종 수정 일시',

    CONSTRAINT PK_SUPPLIER PRIMARY KEY (SUPPLIER_ID),
    CONSTRAINT CK_SUPPLIER_STATUS
        CHECK (OPERATION_STATUS IN ('ACTIVE', 'INACTIVE', 'CLOSED'))
) COMMENT = '외부 발주처 정보를 관리하는 테이블';


/* =========================================================
   2. SUPPLIER_PRODUCT - 발주처상품
========================================================= */
CREATE TABLE SUPPLIER_PRODUCT
(
    SUPPLIER_PRODUCT_ID BIGINT AUTO_INCREMENT                 NOT NULL COMMENT '발주처 상품 고유 번호',
    SUPPLIER_ID         BIGINT                                NOT NULL COMMENT '상품을 취급하는 발주처 고유 번호',
    EXTERNAL_PRODUCT_ID VARCHAR(100)                          NOT NULL COMMENT '외부 발주처 시스템의 상품 식별값',
    PRODUCT_NAME        VARCHAR(200)                          NOT NULL COMMENT '발주처 상품명',
    SUPPLY_PRICE        BIGINT                                NOT NULL COMMENT '상품 공급가',
    PRODUCT_STATUS      VARCHAR(20) DEFAULT 'ACTIVE'          NOT NULL COMMENT '발주처 상품 상태: ACTIVE, INACTIVE, DISCONTINUED',
    CREATED_AT          DATETIME    DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '발주처 상품 등록 일시',
    UPDATED_AT          DATETIME                              NULL COMMENT '발주처 상품 정보 최종 수정 일시',

    CONSTRAINT PK_SUPPLIER_PRODUCT PRIMARY KEY (SUPPLIER_PRODUCT_ID),

    CONSTRAINT FK_SUPPLIER_PRODUCT_SUPPLIER
        FOREIGN KEY (SUPPLIER_ID)
            REFERENCES SUPPLIER (SUPPLIER_ID),

    CONSTRAINT UK_SUPPLIER_PRODUCT_EXTERNAL
        UNIQUE (SUPPLIER_ID, EXTERNAL_PRODUCT_ID),

    CONSTRAINT CK_SUPPLIER_PRODUCT_PRICE
        CHECK (SUPPLY_PRICE >= 0),

    CONSTRAINT CK_SUPPLIER_PRODUCT_STATUS
        CHECK (PRODUCT_STATUS IN ('ACTIVE', 'INACTIVE', 'DISCONTINUED'))
) COMMENT = '외부 발주처에서 취급하는 상품 정보를 관리하는 테이블';


/* =========================================================
   3. SUPPLIER_INVENTORY - 발주처재고
========================================================= */
CREATE TABLE SUPPLIER_INVENTORY
(
    SUPPLIER_ID         BIGINT                             NOT NULL COMMENT '재고를 보유한 발주처 고유 번호',
    SUPPLIER_PRODUCT_ID BIGINT                             NOT NULL COMMENT '재고 대상 발주처 상품 고유 번호',
    CURRENT_QUANTITY    BIGINT   DEFAULT 0                 NOT NULL COMMENT '발주처의 현재 재고 수량',
    CREATED_AT          DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '발주처 재고 정보 등록 일시',
    UPDATED_AT          DATETIME                           NULL COMMENT '발주처 재고 정보 최종 수정 일시',

    CONSTRAINT PK_SUPPLIER_INVENTORY
        PRIMARY KEY (SUPPLIER_ID, SUPPLIER_PRODUCT_ID),

    CONSTRAINT FK_SUPPLIER_INVENTORY_SUPPLIER
        FOREIGN KEY (SUPPLIER_ID)
            REFERENCES SUPPLIER (SUPPLIER_ID),

    CONSTRAINT FK_SUPPLIER_INVENTORY_PRODUCT
        FOREIGN KEY (SUPPLIER_PRODUCT_ID)
            REFERENCES SUPPLIER_PRODUCT (SUPPLIER_PRODUCT_ID),

    CONSTRAINT CK_SUPPLIER_INVENTORY_QTY
        CHECK (CURRENT_QUANTITY >= 0)
) COMMENT = '외부 발주처별 상품 재고 수량을 관리하는 테이블';


/* =========================================================
   4. EXTERNAL_ORDER_RECEIPT - 외부발주접수
========================================================= */
CREATE TABLE EXTERNAL_ORDER_RECEIPT
(
    EXTERNAL_ORDER_RECEIPT_ID BIGINT AUTO_INCREMENT                 NOT NULL COMMENT '외부 발주 접수 고유 번호',
    SUPPLIER_ID               BIGINT                                NOT NULL COMMENT '발주를 접수한 발주처 고유 번호',
    SUPPLIER_PRODUCT_ID       BIGINT                                NOT NULL COMMENT '발주 접수 상품 고유 번호',
    INTERNAL_ORDER_REQUEST_ID VARCHAR(100)                          NOT NULL COMMENT '내부 시스템의 발주 요청 식별값',
    REQUEST_STORE_NAME        VARCHAR(100)                          NOT NULL COMMENT '발주를 요청한 입점매장명',
    REQUEST_QUANTITY          BIGINT                                NOT NULL COMMENT '내부 시스템에서 요청한 발주 수량',
    APPROVED_QUANTITY         BIGINT                                NULL COMMENT '내부 시스템에서 승인된 발주 수량',
    RECEIPT_STATUS            VARCHAR(30) DEFAULT 'RECEIVED'        NOT NULL COMMENT '외부 발주 접수 상태: RECEIVED, APPROVED, REJECTED, PROCESSING, SHIPPED, CANCELED',
    CREATED_AT                DATETIME    DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '외부 발주 접수 등록 일시',
    UPDATED_AT                DATETIME                              NULL COMMENT '외부 발주 접수 정보 최종 수정 일시',

    CONSTRAINT PK_EXTERNAL_ORDER_RECEIPT
        PRIMARY KEY (EXTERNAL_ORDER_RECEIPT_ID),

    CONSTRAINT FK_EXTERNAL_ORDER_RECEIPT_SUPPLIER
        FOREIGN KEY (SUPPLIER_ID)
            REFERENCES SUPPLIER (SUPPLIER_ID),

    CONSTRAINT FK_EXTERNAL_ORDER_RECEIPT_PRODUCT
        FOREIGN KEY (SUPPLIER_PRODUCT_ID)
            REFERENCES SUPPLIER_PRODUCT (SUPPLIER_PRODUCT_ID),

    CONSTRAINT UK_EXTERNAL_ORDER_RECEIPT_INTERNAL
        UNIQUE (INTERNAL_ORDER_REQUEST_ID),

    CONSTRAINT CK_EXTERNAL_ORDER_RECEIPT_REQ_QTY
        CHECK (REQUEST_QUANTITY > 0),

    CONSTRAINT CK_EXTERNAL_ORDER_RECEIPT_APP_QTY
        CHECK (APPROVED_QUANTITY IS NULL OR APPROVED_QUANTITY >= 0),

    CONSTRAINT CK_EXTERNAL_ORDER_RECEIPT_STATUS
        CHECK (
            RECEIPT_STATUS IN (
                               'RECEIVED',
                               'APPROVED',
                               'REJECTED',
                               'PROCESSING',
                               'SHIPPED',
                               'CANCELED'
                )
            )
) COMMENT = '내부 시스템에서 전송한 발주 요청을 외부 발주처가 접수한 내역을 관리하는 테이블';


/* =========================================================
   5. EXTERNAL_SHIPMENT - 외부출고처리
========================================================= */
CREATE TABLE EXTERNAL_SHIPMENT
(
    EXTERNAL_SHIPMENT_ID      BIGINT AUTO_INCREMENT                 NOT NULL COMMENT '외부 출고 처리 고유 번호',
    EXTERNAL_ORDER_RECEIPT_ID BIGINT                                NOT NULL COMMENT '출고 처리 대상 외부 발주 접수 고유 번호',
    SHIPMENT_QUANTITY         BIGINT                                NOT NULL COMMENT '출고 처리된 수량',
    SHIPMENT_STATUS           VARCHAR(30) DEFAULT 'SHIPPED'         NOT NULL COMMENT '출고 처리 상태: READY, SHIPPED, CANCELED, FAILED',
    CREATED_AT                DATETIME    DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '외부 출고 처리 등록 일시',
    UPDATED_AT                DATETIME                              NULL COMMENT '외부 출고 처리 정보 최종 수정 일시',

    CONSTRAINT PK_EXTERNAL_SHIPMENT
        PRIMARY KEY (EXTERNAL_SHIPMENT_ID),

    CONSTRAINT FK_EXTERNAL_SHIPMENT_RECEIPT
        FOREIGN KEY (EXTERNAL_ORDER_RECEIPT_ID)
            REFERENCES EXTERNAL_ORDER_RECEIPT (EXTERNAL_ORDER_RECEIPT_ID),

    CONSTRAINT CK_EXTERNAL_SHIPMENT_QTY
        CHECK (SHIPMENT_QUANTITY > 0),

    CONSTRAINT CK_EXTERNAL_SHIPMENT_STATUS
        CHECK (
            SHIPMENT_STATUS IN (
                                'READY',
                                'SHIPPED',
                                'CANCELED',
                                'FAILED'
                )
            )
) COMMENT = '외부 발주처에서 처리한 상품 출고 내역을 관리하는 테이블';

CREATE TRIGGER TRG_SUPPLIER_UPD_AT
    BEFORE UPDATE
    ON SUPPLIER
    FOR EACH ROW
    SET NEW.UPDATED_AT = NOW();

CREATE TRIGGER TRG_SUP_PRODUCT_UPD_AT
    BEFORE UPDATE
    ON SUPPLIER_PRODUCT
    FOR EACH ROW
    SET NEW.UPDATED_AT = NOW();

CREATE TRIGGER TRG_SUP_INV_UPD_AT
    BEFORE UPDATE
    ON SUPPLIER_INVENTORY
    FOR EACH ROW
    SET NEW.UPDATED_AT = NOW();

CREATE TRIGGER TRG_EXT_ORDER_UPD_AT
    BEFORE UPDATE
    ON EXTERNAL_ORDER_RECEIPT
    FOR EACH ROW
    SET NEW.UPDATED_AT = NOW();

CREATE TRIGGER TRG_EXT_SHIPMENT_UPD_AT
    BEFORE UPDATE
    ON EXTERNAL_SHIPMENT
    FOR EACH ROW
    SET NEW.UPDATED_AT = NOW();

DELIMITER //

CREATE TRIGGER TRG_EXT_SHIPMENT_AI
    AFTER INSERT
    ON EXTERNAL_SHIPMENT
    FOR EACH ROW
BEGIN
    IF NEW.SHIPMENT_STATUS = 'SHIPPED' THEN
        UPDATE EXTERNAL_ORDER_RECEIPT
        SET RECEIPT_STATUS = 'SHIPPED'
        WHERE EXTERNAL_ORDER_RECEIPT_ID = NEW.EXTERNAL_ORDER_RECEIPT_ID;
    ELSEIF NEW.SHIPMENT_STATUS = 'CANCELED' THEN
        UPDATE EXTERNAL_ORDER_RECEIPT
        SET RECEIPT_STATUS = 'CANCELED'
        WHERE EXTERNAL_ORDER_RECEIPT_ID = NEW.EXTERNAL_ORDER_RECEIPT_ID;
    ELSEIF NEW.SHIPMENT_STATUS = 'FAILED' THEN
        UPDATE EXTERNAL_ORDER_RECEIPT
        SET RECEIPT_STATUS = 'PROCESSING'
        WHERE EXTERNAL_ORDER_RECEIPT_ID = NEW.EXTERNAL_ORDER_RECEIPT_ID;
    ELSEIF NEW.SHIPMENT_STATUS = 'READY' THEN
        UPDATE EXTERNAL_ORDER_RECEIPT
        SET RECEIPT_STATUS = 'PROCESSING'
        WHERE EXTERNAL_ORDER_RECEIPT_ID = NEW.EXTERNAL_ORDER_RECEIPT_ID;
    END IF;
END //

DELIMITER ;

COMMIT;
