/* =========================================================
   MariaDB DDL - External Supplier DB
   Converted from Oracle 21c DDL
========================================================= */

SET FOREIGN_KEY_CHECKS = 0;

DROP TRIGGER IF EXISTS TRG_SUPPLIER_UPD_AT;
DROP TRIGGER IF EXISTS TRG_SUP_PRODUCT_UPD_AT;
DROP TRIGGER IF EXISTS TRG_SUP_INV_UPD_AT;
DROP TRIGGER IF EXISTS TRG_EXT_ORDER_UPD_AT;
DROP TRIGGER IF EXISTS TRG_EXT_SHIPMENT_UPD_AT;
DROP TRIGGER IF EXISTS TRG_EXT_ORDER_RECEIPT_AU;

DROP TABLE IF EXISTS EXTERNAL_SHIPMENT;
DROP TABLE IF EXISTS EXTERNAL_ORDER_RECEIPT;
DROP TABLE IF EXISTS SUPPLIER_INVENTORY;
DROP TABLE IF EXISTS SUPPLIER_PRODUCT;
DROP TABLE IF EXISTS SUPPLIER;

SET FOREIGN_KEY_CHECKS = 1;

/* =========================================================
   1. SUPPLIER - 발주처
========================================================= */
CREATE TABLE SUPPLIER
(
    SUPPLIER_ID      BIGINT AUTO_INCREMENT                 NOT NULL COMMENT '발주처ID',
    SUPPLIER_NAME    VARCHAR(100)                          NOT NULL COMMENT '발주처명',
    SUPPLIER_TYPE    VARCHAR(50)                           NOT NULL COMMENT '발주처유형',
    ADDRESS          VARCHAR(300) COMMENT '주소',
    PHONE_NUMBER     VARCHAR(30) COMMENT '연락처',
    OPERATION_STATUS VARCHAR(20) DEFAULT 'ACTIVE'          NOT NULL COMMENT '운영상태',
    CREATED_AT       DATETIME    DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '등록일자',
    UPDATED_AT       DATETIME                              NULL COMMENT '최종수정일자',

    CONSTRAINT PK_SUPPLIER PRIMARY KEY (SUPPLIER_ID),
    CONSTRAINT CK_SUPPLIER_STATUS
        CHECK (OPERATION_STATUS IN ('ACTIVE', 'INACTIVE', 'CLOSED'))
) COMMENT = '발주처';


/* =========================================================
   2. SUPPLIER_PRODUCT - 발주처상품
========================================================= */
CREATE TABLE SUPPLIER_PRODUCT
(
    SUPPLIER_PRODUCT_ID BIGINT AUTO_INCREMENT                 NOT NULL COMMENT '발주처상품ID',
    SUPPLIER_ID         BIGINT                                NOT NULL COMMENT '발주처ID',
    EXTERNAL_PRODUCT_ID VARCHAR(100)                          NOT NULL COMMENT '외부상품ID',
    PRODUCT_NAME        VARCHAR(200)                          NOT NULL COMMENT '상품명',
    SUPPLY_PRICE        BIGINT                                NOT NULL COMMENT '공급가',
    PRODUCT_STATUS      VARCHAR(20) DEFAULT 'ACTIVE'          NOT NULL COMMENT '상품상태',
    CREATED_AT          DATETIME    DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '등록일자',
    UPDATED_AT          DATETIME                              NULL COMMENT '최종수정일자',

    CONSTRAINT PK_SUPPLIER_PRODUCT PRIMARY KEY (SUPPLIER_PRODUCT_ID),

    CONSTRAINT FK_SUPPLIER_PRODUCT_SUPPLIER
        FOREIGN KEY (SUPPLIER_ID)
            REFERENCES SUPPLIER (SUPPLIER_ID),

    CONSTRAINT UK_SUPPLIER_PRODUCT_EXTERNAL
        UNIQUE (SUPPLIER_ID, EXTERNAL_PRODUCT_ID),

    CONSTRAINT CK_SUPPLIER_PRODUCT_PRICE
        CHECK (SUPPLY_PRICE >= 0),

    CONSTRAINT CK_SUPPLIER_PRODUCT_STATUS
        CHECK (PRODUCT_STATUS IN ('ACTIVE', 'INACTIVE', 'DISCONTINUED'))
) COMMENT = '발주처상품';


/* =========================================================
   3. SUPPLIER_INVENTORY - 발주처재고
========================================================= */
CREATE TABLE SUPPLIER_INVENTORY
(
    SUPPLIER_ID         BIGINT                             NOT NULL COMMENT '발주처ID',
    SUPPLIER_PRODUCT_ID BIGINT                             NOT NULL COMMENT '발주처상품ID',
    CURRENT_QUANTITY    BIGINT   DEFAULT 0                 NOT NULL COMMENT '현재수량',
    CREATED_AT          DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '등록일자',
    UPDATED_AT          DATETIME                           NULL COMMENT '최종수정일자',

    CONSTRAINT PK_SUPPLIER_INVENTORY
        PRIMARY KEY (SUPPLIER_ID, SUPPLIER_PRODUCT_ID),

    CONSTRAINT FK_SUPPLIER_INVENTORY_SUPPLIER
        FOREIGN KEY (SUPPLIER_ID)
            REFERENCES SUPPLIER (SUPPLIER_ID),

    CONSTRAINT FK_SUPPLIER_INVENTORY_PRODUCT
        FOREIGN KEY (SUPPLIER_PRODUCT_ID)
            REFERENCES SUPPLIER_PRODUCT (SUPPLIER_PRODUCT_ID),

    CONSTRAINT CK_SUPPLIER_INVENTORY_QTY
        CHECK (CURRENT_QUANTITY >= 0)
) COMMENT = '발주처재고';


/* =========================================================
   4. EXTERNAL_ORDER_RECEIPT - 외부발주접수
========================================================= */
CREATE TABLE EXTERNAL_ORDER_RECEIPT
(
    EXTERNAL_ORDER_RECEIPT_ID BIGINT AUTO_INCREMENT                 NOT NULL COMMENT '외부발주접수ID',
    SUPPLIER_ID               BIGINT                                NOT NULL COMMENT '발주처ID',
    SUPPLIER_PRODUCT_ID       BIGINT                                NOT NULL COMMENT '발주처상품ID',
    INTERNAL_ORDER_REQUEST_ID VARCHAR(100)                          NOT NULL COMMENT '내부발주요청ID',
    REQUEST_STORE_NAME        VARCHAR(100)                          NOT NULL COMMENT '요청매장명',
    REQUEST_QUANTITY          BIGINT                                NOT NULL COMMENT '요청수량',
    APPROVED_QUANTITY         BIGINT                                NULL COMMENT '승인수량',
    RECEIPT_STATUS            VARCHAR(30) DEFAULT 'RECEIVED'        NOT NULL COMMENT '접수상태',
    CREATED_AT                DATETIME    DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '등록일자',
    UPDATED_AT                DATETIME                              NULL COMMENT '최종수정일자',

    CONSTRAINT PK_EXTERNAL_ORDER_RECEIPT
        PRIMARY KEY (EXTERNAL_ORDER_RECEIPT_ID),

    CONSTRAINT FK_EXTERNAL_ORDER_RECEIPT_SUPPLIER
        FOREIGN KEY (SUPPLIER_ID)
            REFERENCES SUPPLIER (SUPPLIER_ID),

    CONSTRAINT FK_EXTERNAL_ORDER_RECEIPT_PRODUCT
        FOREIGN KEY (SUPPLIER_PRODUCT_ID)
            REFERENCES SUPPLIER_PRODUCT (SUPPLIER_PRODUCT_ID),

    CONSTRAINT UK_EXTERNAL_ORDER_RECEIPT_INTERNAL
        UNIQUE (INTERNAL_ORDER_REQUEST_ID),

    CONSTRAINT CK_EXTERNAL_ORDER_RECEIPT_REQ_QTY
        CHECK (REQUEST_QUANTITY > 0),

    CONSTRAINT CK_EXTERNAL_ORDER_RECEIPT_APP_QTY
        CHECK (APPROVED_QUANTITY IS NULL OR APPROVED_QUANTITY >= 0),

    CONSTRAINT CK_EXTERNAL_ORDER_RECEIPT_STATUS
        CHECK (
            RECEIPT_STATUS IN (
                               'RECEIVED',
                               'REJECTED',
                               'SHIPPED'
                )
            ),
    CONSTRAINT CK_EXTERNAL_ORDER_RECEIPT_STATUS_QTY
        CHECK (
            (RECEIPT_STATUS = 'SHIPPED' AND APPROVED_QUANTITY > 0)
                OR
            (RECEIPT_STATUS = 'REJECTED' AND APPROVED_QUANTITY IS NULL)
                OR
            (RECEIPT_STATUS = 'RECEIVED')
            )
) COMMENT = '외부발주접수';


/* =========================================================
   5. EXTERNAL_SHIPMENT - 외부출고처리
========================================================= */
CREATE TABLE EXTERNAL_SHIPMENT
(
    EXTERNAL_SHIPMENT_ID      BIGINT AUTO_INCREMENT                 NOT NULL COMMENT '외부출고처리ID',
    EXTERNAL_ORDER_RECEIPT_ID BIGINT                                NOT NULL COMMENT '외부발주접수ID',
    SHIPMENT_QUANTITY         BIGINT                                NOT NULL COMMENT '출고수량',
    SHIPMENT_STATUS           VARCHAR(30) DEFAULT 'SHIPPED'         NOT NULL COMMENT '출고상태',
    CREATED_AT                DATETIME    DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '등록일자',
    UPDATED_AT                DATETIME                              NULL COMMENT '최종수정일자',

    CONSTRAINT PK_EXTERNAL_SHIPMENT
        PRIMARY KEY (EXTERNAL_SHIPMENT_ID),

    CONSTRAINT UK_EXTERNAL_SHIPMENT_RECEIPT
        UNIQUE (EXTERNAL_ORDER_RECEIPT_ID),

    CONSTRAINT FK_EXTERNAL_SHIPMENT_RECEIPT
        FOREIGN KEY (EXTERNAL_ORDER_RECEIPT_ID)
            REFERENCES EXTERNAL_ORDER_RECEIPT (EXTERNAL_ORDER_RECEIPT_ID),

    CONSTRAINT CK_EXTERNAL_SHIPMENT_QTY
        CHECK (SHIPMENT_QUANTITY > 0),

    CONSTRAINT CK_EXTERNAL_SHIPMENT_STATUS
        CHECK (
            SHIPMENT_STATUS IN (
                                'SHIPPED'
                )
            )
) COMMENT = '외부출고처리';

CREATE TRIGGER TRG_SUPPLIER_UPD_AT
    BEFORE UPDATE
    ON SUPPLIER
    FOR EACH ROW
    SET NEW.UPDATED_AT = NOW();

CREATE TRIGGER TRG_SUP_PRODUCT_UPD_AT
    BEFORE UPDATE
    ON SUPPLIER_PRODUCT
    FOR EACH ROW
    SET NEW.UPDATED_AT = NOW();

CREATE TRIGGER TRG_SUP_INV_UPD_AT
    BEFORE UPDATE
    ON SUPPLIER_INVENTORY
    FOR EACH ROW
    SET NEW.UPDATED_AT = NOW();

CREATE TRIGGER TRG_EXT_ORDER_UPD_AT
    BEFORE UPDATE
    ON EXTERNAL_ORDER_RECEIPT
    FOR EACH ROW
    SET NEW.UPDATED_AT = NOW();

CREATE TRIGGER TRG_EXT_SHIPMENT_UPD_AT
    BEFORE UPDATE
    ON EXTERNAL_SHIPMENT
    FOR EACH ROW
    SET NEW.UPDATED_AT = NOW();

DELIMITER //

CREATE TRIGGER TRG_EXT_ORDER_RECEIPT_AU
    AFTER UPDATE
    ON EXTERNAL_ORDER_RECEIPT
    FOR EACH ROW
BEGIN
    IF NEW.RECEIPT_STATUS = 'SHIPPED'
        AND OLD.RECEIPT_STATUS <> NEW.RECEIPT_STATUS THEN

        INSERT INTO EXTERNAL_SHIPMENT (
            EXTERNAL_ORDER_RECEIPT_ID,
            SHIPMENT_QUANTITY,
            SHIPMENT_STATUS
        )
        VALUES (
                   NEW.EXTERNAL_ORDER_RECEIPT_ID,
                NEW.APPROVED_QUANTITY,
                   'SHIPPED'
               )
        ON DUPLICATE KEY UPDATE
                             SHIPMENT_QUANTITY = NEW.APPROVED_QUANTITY,
                             SHIPMENT_STATUS = 'SHIPPED',
                             UPDATED_AT = NOW();

    END IF;
END //

DELIMITER ;

COMMIT;
