/* =========================================================
   HIMS Master Data INSERT - IDENTITY 대응 버전
   대상 테이블: ROLE, BRANCH, BRAND, CATEGORY, STORE, PRODUCT, EMPLOYEE
   기준: 현대백화점 물류재고 ERD 데이터 v1.3
   변경 반영:
   - PK 컬럼이 GENERATED BY DEFAULT AS IDENTITY로 변경되어 PK 컬럼은 INSERT에서 제외
   - FK 컬럼은 이름 기반 서브쿼리로 참조
   - CREATED_AT 기본값은 대부분 DEFAULT SYSDATE 사용
========================================================= */

/* =========================================================
   1. ROLE - 권한
========================================================= */
INSERT INTO ROLE (ROLE_NAME,
                  ROLE_DESCRIPTION)
VALUES ('지점관리자',
        '기준 정보 및 전체 현황 관리');

INSERT INTO ROLE (ROLE_NAME,
                  ROLE_DESCRIPTION)
VALUES ('발주처담당자',
        '발주 승인/반려 및 발주처 재고 관리');

INSERT INTO ROLE (ROLE_NAME,
                  ROLE_DESCRIPTION)
VALUES ('입점매장담당자',
        '입점매장 재고 조회 및 발주 요청/입고 확인');

INSERT INTO ROLE (ROLE_NAME,
                  ROLE_DESCRIPTION)
VALUES ('시스템담당자',
        '시스템 전체 직원들 계정 관리, 유지보수 권한');

INSERT INTO ROLE (ROLE_NAME,
                  ROLE_DESCRIPTION)
VALUES ('일반직원',
        '권한없음.');

/* =========================================================
   2. BRANCH - 지점
   Excel 운영상태 '운영' -> DDL CHECK 값 'ACTIVE'로 변환
========================================================= */
INSERT INTO BRANCH (BRANCH_NAME,
                    ADDRESS,
                    PHONE_NUMBER,
                    OPERATION_STATUS)
VALUES ('더현대서울',
        '서울특별시 영등포구 여의대로 108',
        '02-767-2233',
        'ACTIVE');

INSERT INTO BRANCH (BRANCH_NAME,
                    ADDRESS,
                    PHONE_NUMBER,
                    OPERATION_STATUS)
VALUES ('현대백화점 판교점',
        '경기도 성남시 분당구 판교역로146번길 20',
        '031-5170-2233',
        'ACTIVE');

INSERT INTO BRANCH (BRANCH_NAME,
                    ADDRESS,
                    PHONE_NUMBER,
                    OPERATION_STATUS)
VALUES ('현대백화점 무역센터점',
        '서울특별시 강남구 테헤란로 517',
        '02-552-2233',
        'ACTIVE');

/* =========================================================
   3. BRAND - 브랜드
   Excel 운영상태 '운영' -> DDL CHECK 값 'ACTIVE'로 변환
========================================================= */
INSERT INTO BRAND (BRAND_NAME,
                   MANAGER_NAME,
                   PHONE_NUMBER,
                   OPERATION_STATUS)
VALUES ('TIME',
        '김도윤',
        '02-3416-2000',
        'ACTIVE');

INSERT INTO BRAND (BRAND_NAME,
                   MANAGER_NAME,
                   PHONE_NUMBER,
                   OPERATION_STATUS)
VALUES ('SYSTEM',
        '박서연',
        '02-3416-2100',
        'ACTIVE');

INSERT INTO BRAND (BRAND_NAME,
                   MANAGER_NAME,
                   PHONE_NUMBER,
                   OPERATION_STATUS)
VALUES ('MINE',
        '이민재',
        '02-3416-2200',
        'ACTIVE');

INSERT INTO BRAND (BRAND_NAME,
                   MANAGER_NAME,
                   PHONE_NUMBER,
                   OPERATION_STATUS)
VALUES ('THE CASHMERE',
        '최유진',
        '02-3416-2300',
        'ACTIVE');

/* =========================================================
   4. CATEGORY - 카테고리
   상위 카테고리 FK 때문에 부모 카테고리부터 INSERT
========================================================= */
INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES (NULL,
        '의류',
        1,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '의류'),
        '여성의류',
        2,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '여성의류'),
        '여성아우터',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '여성의류'),
        '여성원피스',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '여성의류'),
        '여성니트/탑',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '여성의류'),
        '여성하의',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '의류'),
        '남성의류',
        2,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '남성의류'),
        '남성아우터',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '남성의류'),
        '남성니트/탑',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '남성의류'),
        '남성하의',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES (NULL,
        '가구',
        1,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '가구'),
        '거실가구',
        2,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '거실가구'),
        '소파',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '거실가구'),
        '테이블',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '가구'),
        '침실가구',
        2,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '침실가구'),
        '침대',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '침실가구'),
        '옷장',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '가구'),
        '주방가구',
        2,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '주방가구'),
        '식탁',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '주방가구'),
        '의자',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES (NULL,
        '생활용품',
        1,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '생활용품'),
        '주방용품',
        2,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '주방용품'),
        '식기류',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '주방용품'),
        '조리도구',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '생활용품'),
        '욕실용품',
        2,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '욕실용품'),
        '수건',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '욕실용품'),
        '욕실소품',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '생활용품'),
        '홈데코',
        2,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '홈데코'),
        '조명',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '홈데코'),
        '인테리어소품',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES (NULL,
        '잡화',
        1,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '잡화'),
        '가방',
        2,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '가방'),
        '여성가방',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '가방'),
        '남성가방',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '잡화'),
        '신발',
        2,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '신발'),
        '여성신발',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '신발'),
        '남성신발',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '잡화'),
        '액세서리',
        2,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '액세서리'),
        '주얼리',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '액세서리'),
        '스카프/머플러',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES (NULL,
        '식품',
        1,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '식품'),
        '신선식품',
        2,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '신선식품'),
        '과일',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '신선식품'),
        '정육',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '식품'),
        '가공식품',
        2,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '가공식품'),
        '간편식',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '가공식품'),
        '소스/조미료',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '식품'),
        '델리',
        2,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '델리'),
        '도시락',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '델리'),
        '샐러드',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES (NULL,
        '기타',
        1,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '기타'),
        '기타상품',
        2,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '기타상품'),
        '시즌기획상품',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '기타상품'),
        '행사상품',
        3,
        'Y');

/* =========================================================
   5. STORE - 입점매장
   Excel 운영상태 '운영' -> DDL CHECK 값 'ACTIVE'로 변환
========================================================= */
INSERT INTO STORE (BRANCH_ID,
                   BRAND_ID,
                   STORE_NAME,
                   FLOOR_INFO,
                   STORE_LOCATION,
                   OPERATION_STATUS)
VALUES ((SELECT BRANCH_ID FROM BRANCH WHERE BRANCH_NAME = '더현대서울'),
        (SELECT BRAND_ID FROM BRAND WHERE BRAND_NAME = 'THE CASHMERE'),
        'THE CASHMERE 더현대서울점',
        '3F',
        '여성패션존 A-12',
        'ACTIVE');

INSERT INTO STORE (BRANCH_ID,
                   BRAND_ID,
                   STORE_NAME,
                   FLOOR_INFO,
                   STORE_LOCATION,
                   OPERATION_STATUS)
VALUES ((SELECT BRANCH_ID FROM BRANCH WHERE BRANCH_NAME = '현대백화점 판교점'),
        (SELECT BRAND_ID FROM BRAND WHERE BRAND_NAME = 'TIME'),
        'TIME 판교점',
        '2F',
        '여성패션존 B-04',
        'ACTIVE');

INSERT INTO STORE (BRANCH_ID,
                   BRAND_ID,
                   STORE_NAME,
                   FLOOR_INFO,
                   STORE_LOCATION,
                   OPERATION_STATUS)
VALUES ((SELECT BRANCH_ID FROM BRANCH WHERE BRANCH_NAME = '현대백화점 무역센터점'),
        (SELECT BRAND_ID FROM BRAND WHERE BRAND_NAME = 'SYSTEM'),
        'SYSTEM 무역센터점',
        '4F',
        '영캐주얼존 C-03',
        'ACTIVE');

INSERT INTO STORE (BRANCH_ID,
                   BRAND_ID,
                   STORE_NAME,
                   FLOOR_INFO,
                   STORE_LOCATION,
                   OPERATION_STATUS)
VALUES ((SELECT BRANCH_ID FROM BRANCH WHERE BRANCH_NAME = '더현대서울'),
        (SELECT BRAND_ID FROM BRAND WHERE BRAND_NAME = 'MINE'),
        'MINE 더현대서울점',
        '3F',
        '여성패션존 A-15',
        'ACTIVE');

/* =========================================================
   6. PRODUCT - 상품
   Excel 상품상태 '판매 가능' -> DDL CHECK 값 'ON_SALE'로 변환
========================================================= */
INSERT INTO PRODUCT (BRAND_ID,
                     CATEGORY_ID,
                     PRODUCT_NAME,
                     PRICE,
                     SEASON_TYPE,
                     PRODUCT_STATUS,
                     CREATED_AT)
VALUES ((SELECT BRAND_ID FROM BRAND WHERE BRAND_NAME = 'TIME'),
        (SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '여성아우터'),
        'TIME 울 블렌드 재킷',
        398000,
        '가을/겨울',
        'ON_SALE',
        TO_DATE('2026-02-10', 'YYYY-MM-DD'));

INSERT INTO PRODUCT (BRAND_ID,
                     CATEGORY_ID,
                     PRODUCT_NAME,
                     PRICE,
                     SEASON_TYPE,
                     PRODUCT_STATUS,
                     CREATED_AT)
VALUES ((SELECT BRAND_ID FROM BRAND WHERE BRAND_NAME = 'TIME'),
        (SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '여성원피스'),
        'TIME 썸머 린넨 원피스',
        268000,
        '봄/여름',
        'ON_SALE',
        TO_DATE('2026-03-05', 'YYYY-MM-DD'));

INSERT INTO PRODUCT (BRAND_ID,
                     CATEGORY_ID,
                     PRODUCT_NAME,
                     PRICE,
                     SEASON_TYPE,
                     PRODUCT_STATUS,
                     CREATED_AT)
VALUES ((SELECT BRAND_ID FROM BRAND WHERE BRAND_NAME = 'SYSTEM'),
        (SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '여성니트/탑'),
        'SYSTEM 캐시미어 니트',
        328000,
        '가을/겨울',
        'ON_SALE',
        TO_DATE('2026-02-18', 'YYYY-MM-DD'));

INSERT INTO PRODUCT (BRAND_ID,
                     CATEGORY_ID,
                     PRODUCT_NAME,
                     PRICE,
                     SEASON_TYPE,
                     PRODUCT_STATUS,
                     CREATED_AT)
VALUES ((SELECT BRAND_ID FROM BRAND WHERE BRAND_NAME = 'MINE'),
        (SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '여성아우터'),
        'MINE 트렌치 코트',
        528000,
        '봄/여름',
        'ON_SALE',
        TO_DATE('2026-03-12', 'YYYY-MM-DD'));

INSERT INTO PRODUCT (BRAND_ID,
                     CATEGORY_ID,
                     PRODUCT_NAME,
                     PRICE,
                     SEASON_TYPE,
                     PRODUCT_STATUS,
                     CREATED_AT)
VALUES ((SELECT BRAND_ID FROM BRAND WHERE BRAND_NAME = 'THE CASHMERE'),
        (SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '여성니트/탑'),
        'THE CASHMERE 홀가먼트 니트',
        458000,
        '가을/겨울',
        'ON_SALE',
        TO_DATE('2026-02-25', 'YYYY-MM-DD'));

/* =========================================================
   7. EMPLOYEE - 직원
   주의:
   - Excel에는 발주처ID 컬럼이 있지만 현재 EMPLOYEE DDL에는 해당 컬럼이 없으므로 제외
   - 시스템담당자는 BRANCH_ID, STORE_ID를 NULL 처리
   - 지점관리자는 소속 BRANCH_ID를 지정하고 STORE_ID만 NULL 처리
   - STORE_ID가 없는 발주처담당자는 STORE_ID만 NULL 처리
========================================================= */
INSERT INTO EMPLOYEE (ROLE_ID,
                      BRANCH_ID,
                      STORE_ID,
                      LOGIN_ID,
                      PASSWORD,
                      EMPLOYEE_NAME,
                      PHONE_NUMBER,
                      IS_ACTIVE)
VALUES ((SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = '지점관리자'),
        (SELECT BRANCH_ID FROM BRANCH WHERE BRANCH_NAME = '더현대서울'),
        NULL,
        'admin01',
        'pass1234',
        '정관리',
        '010-1000-0001',
        'Y');

INSERT INTO EMPLOYEE (ROLE_ID,
                      BRANCH_ID,
                      STORE_ID,
                      LOGIN_ID,
                      PASSWORD,
                      EMPLOYEE_NAME,
                      PHONE_NUMBER,
                      IS_ACTIVE)
VALUES ((SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = '발주처담당자'),
        (SELECT BRANCH_ID FROM BRANCH WHERE BRANCH_NAME = '현대백화점 판교점'),
        NULL,
        'logi_time',
        'pass1234',
        '오물류',
        '010-1000-0002',
        'Y');

INSERT INTO EMPLOYEE (ROLE_ID,
                      BRANCH_ID,
                      STORE_ID,
                      LOGIN_ID,
                      PASSWORD,
                      EMPLOYEE_NAME,
                      PHONE_NUMBER,
                      IS_ACTIVE)
VALUES ((SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = '발주처담당자'),
        (SELECT BRANCH_ID FROM BRANCH WHERE BRANCH_NAME = '현대백화점 무역센터점'),
        NULL,
        'logi_system',
        'pass1234',
        '문출고',
        '010-1000-0003',
        'Y');

INSERT INTO EMPLOYEE (ROLE_ID,
                      BRANCH_ID,
                      STORE_ID,
                      LOGIN_ID,
                      PASSWORD,
                      EMPLOYEE_NAME,
                      PHONE_NUMBER,
                      IS_ACTIVE)
VALUES ((SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = '발주처담당자'),
        (SELECT BRANCH_ID FROM BRANCH WHERE BRANCH_NAME = '더현대서울'),
        NULL,
        'logi_mine',
        'pass1234',
        '최배송',
        '010-1000-0004',
        'Y');

INSERT INTO EMPLOYEE (ROLE_ID,
                      BRANCH_ID,
                      STORE_ID,
                      LOGIN_ID,
                      PASSWORD,
                      EMPLOYEE_NAME,
                      PHONE_NUMBER,
                      IS_ACTIVE)
VALUES ((SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = '발주처담당자'),
        (SELECT BRANCH_ID FROM BRANCH WHERE BRANCH_NAME = '더현대서울'),
        NULL,
        'logi_cashmere',
        'pass1234',
        '서물류',
        '010-1000-0009',
        'Y');

INSERT INTO EMPLOYEE (ROLE_ID,
                      BRANCH_ID,
                      STORE_ID,
                      LOGIN_ID,
                      PASSWORD,
                      EMPLOYEE_NAME,
                      PHONE_NUMBER,
                      IS_ACTIVE)
VALUES ((SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = '입점매장담당자'),
        (SELECT BRANCH_ID FROM BRANCH WHERE BRANCH_NAME = '더현대서울'),
        (SELECT STORE_ID FROM STORE WHERE STORE_NAME = 'THE CASHMERE 더현대서울점'),
        'store_cashmere',
        'pass1234',
        '김매장',
        '010-1000-0005',
        'Y');

INSERT INTO EMPLOYEE (ROLE_ID,
                      BRANCH_ID,
                      STORE_ID,
                      LOGIN_ID,
                      PASSWORD,
                      EMPLOYEE_NAME,
                      PHONE_NUMBER,
                      IS_ACTIVE)
VALUES ((SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = '입점매장담당자'),
        (SELECT BRANCH_ID FROM BRANCH WHERE BRANCH_NAME = '현대백화점 판교점'),
        (SELECT STORE_ID FROM STORE WHERE STORE_NAME = 'TIME 판교점'),
        'store_time',
        'pass1234',
        '이담당',
        '010-1000-0006',
        'Y');

INSERT INTO EMPLOYEE (ROLE_ID,
                      BRANCH_ID,
                      STORE_ID,
                      LOGIN_ID,
                      PASSWORD,
                      EMPLOYEE_NAME,
                      PHONE_NUMBER,
                      IS_ACTIVE)
VALUES ((SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = '입점매장담당자'),
        (SELECT BRANCH_ID FROM BRANCH WHERE BRANCH_NAME = '현대백화점 무역센터점'),
        (SELECT STORE_ID FROM STORE WHERE STORE_NAME = 'SYSTEM 무역센터점'),
        'store_system',
        'pass1234',
        '박담당',
        '010-1000-0007',
        'Y');

INSERT INTO EMPLOYEE (ROLE_ID,
                      BRANCH_ID,
                      STORE_ID,
                      LOGIN_ID,
                      PASSWORD,
                      EMPLOYEE_NAME,
                      PHONE_NUMBER,
                      IS_ACTIVE)
VALUES ((SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = '입점매장담당자'),
        (SELECT BRANCH_ID FROM BRANCH WHERE BRANCH_NAME = '더현대서울'),
        (SELECT STORE_ID FROM STORE WHERE STORE_NAME = 'MINE 더현대서울점'),
        'store_mine',
        'pass1234',
        '한담당',
        '010-1000-0008',
        'Y');

INSERT INTO EMPLOYEE (ROLE_ID,
                      BRANCH_ID,
                      STORE_ID,
                      LOGIN_ID,
                      PASSWORD,
                      EMPLOYEE_NAME,
                      PHONE_NUMBER,
                      IS_ACTIVE)
VALUES ((SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = '시스템담당자'),
        NULL,
        NULL,
        'system_mine',
        'pass1234',
        '시담당',
        '010-1000-0009',
        'Y');


/* =========================================================
   외부 DB 연동 ID 기준
   - SUPPLIER_INTEGRATION.EXTERNAL_SUPPLIER_ID = MariaDB SUPPLIER.SUPPLIER_ID
   - Oracle PRODUCT.PRODUCT_ID = MariaDB SUPPLIER_PRODUCT.SUPPLIER_PRODUCT_ID
   - Java 코드가 내부 ID를 MariaDB INSERT에 넘기는 구조와 맞춤
========================================================= */

INSERT INTO SUPPLIER_INTEGRATION (BRAND_ID,
                                  EXTERNAL_SUPPLIER_ID,
                                  SUPPLIER_NAME,
                                  API_ENDPOINT,
                                  INTEGRATION_STATUS)
VALUES ((SELECT BRAND_ID FROM BRAND WHERE BRAND_NAME = 'TIME'),
        '1',
        'TIME 한섬 본사 발주팀',
        'https://supplier.example.com/time/orders',
        'ACTIVE');

INSERT INTO SUPPLIER_INTEGRATION (BRAND_ID,
                                  EXTERNAL_SUPPLIER_ID,
                                  SUPPLIER_NAME,
                                  API_ENDPOINT,
                                  INTEGRATION_STATUS)
VALUES ((SELECT BRAND_ID FROM BRAND WHERE BRAND_NAME = 'SYSTEM'),
        '2',
        'SYSTEM 한섬 본사 발주팀',
        'https://supplier.example.com/system/orders',
        'ACTIVE');

INSERT INTO SUPPLIER_INTEGRATION (BRAND_ID,
                                  EXTERNAL_SUPPLIER_ID,
                                  SUPPLIER_NAME,
                                  API_ENDPOINT,
                                  INTEGRATION_STATUS)
VALUES ((SELECT BRAND_ID FROM BRAND WHERE BRAND_NAME = 'MINE'),
        '3',
        'MINE 한섬 본사 발주팀',
        'https://supplier.example.com/mine/orders',
        'ACTIVE');

INSERT INTO SUPPLIER_INTEGRATION (BRAND_ID,
                                  EXTERNAL_SUPPLIER_ID,
                                  SUPPLIER_NAME,
                                  API_ENDPOINT,
                                  INTEGRATION_STATUS)
VALUES ((SELECT BRAND_ID FROM BRAND WHERE BRAND_NAME = 'THE CASHMERE'),
        '4',
        'THE CASHMERE 한섬 본사 발주팀',
        'https://supplier.example.com/cashmere/orders',
        'ACTIVE');

INSERT INTO STORE_INVENTORY (STORE_ID,
                             PRODUCT_ID,
                             CURRENT_QUANTITY,
                             SAFETY_QUANTITY)
VALUES ((SELECT STORE_ID FROM STORE WHERE STORE_NAME = 'TIME 판교점'),
        (SELECT PRODUCT_ID FROM PRODUCT WHERE PRODUCT_NAME = 'TIME 울 블렌드 재킷'),
        8,
        5);

INSERT INTO STORE_INVENTORY (STORE_ID,
                             PRODUCT_ID,
                             CURRENT_QUANTITY,
                             SAFETY_QUANTITY)
VALUES ((SELECT STORE_ID FROM STORE WHERE STORE_NAME = 'TIME 판교점'),
        (SELECT PRODUCT_ID FROM PRODUCT WHERE PRODUCT_NAME = 'TIME 썸머 린넨 원피스'),
        3,
        5);

INSERT INTO STORE_INVENTORY (STORE_ID,
                             PRODUCT_ID,
                             CURRENT_QUANTITY,
                             SAFETY_QUANTITY)
VALUES ((SELECT STORE_ID FROM STORE WHERE STORE_NAME = 'SYSTEM 무역센터점'),
        (SELECT PRODUCT_ID FROM PRODUCT WHERE PRODUCT_NAME = 'SYSTEM 캐시미어 니트'),
        4,
        6);

INSERT INTO STORE_INVENTORY (STORE_ID,
                             PRODUCT_ID,
                             CURRENT_QUANTITY,
                             SAFETY_QUANTITY)
VALUES ((SELECT STORE_ID FROM STORE WHERE STORE_NAME = 'MINE 더현대서울점'),
        (SELECT PRODUCT_ID FROM PRODUCT WHERE PRODUCT_NAME = 'MINE 트렌치 코트'),
        2,
        4);

INSERT INTO STORE_INVENTORY (STORE_ID,
                             PRODUCT_ID,
                             CURRENT_QUANTITY,
                             SAFETY_QUANTITY)
VALUES ((SELECT STORE_ID FROM STORE WHERE STORE_NAME = 'THE CASHMERE 더현대서울점'),
        (SELECT PRODUCT_ID FROM PRODUCT WHERE PRODUCT_NAME = 'THE CASHMERE 홀가먼트 니트'),
        6,
        3);

/* =========================================================
   10~12. 업무 흐름별 발주/승인/입고 더미 데이터
   - 표준 상태 흐름 1, 2-A, 2-B, 3-A, 3-B, 4-A, 4-B, 4-C 전체 포함
   - ORDER_REQUEST_ID는 신규 DB에서 1부터 생성된다는 기준
   - ORDER_APPROVAL 트리거가 있어도 최종 스냅샷 상태가 유지되도록 ORDER_REQUEST를 먼저 최종 상태로 삽입
========================================================= */

INSERT INTO ORDER_REQUEST (STORE_ID, SUPPLIER_INTEGRATION_ID, PRODUCT_ID, REQUEST_EMPLOYEE_ID,
                           APPROVAL_EMPLOYEE_ID, APPROVAL_ROLE_ID, EXTERNAL_ORDER_ID,
                           ORDER_QUANTITY, APPROVED_QUANTITY, REQUEST_REASON, REJECT_REASON,
                           ORDER_STATUS, REQUESTED_AT, APPROVED_AT, REJECTED_AT, SENT_TO_SUPPLIER_AT)
VALUES ((SELECT STORE_ID FROM STORE WHERE STORE_NAME = 'TIME 판교점'),
        (SELECT SUPPLIER_INTEGRATION_ID FROM SUPPLIER_INTEGRATION WHERE EXTERNAL_SUPPLIER_ID = '1'),
        (SELECT PRODUCT_ID FROM PRODUCT WHERE PRODUCT_NAME = 'TIME 썸머 린넨 원피스'),
        (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'store_time'),
        NULL,
        NULL,
        NULL,
        10,
        NULL,
        '안전재고 및 행사 대비 발주 요청',
        NULL,
        'REQUESTED',
        TO_DATE('2026-05-01 10:07:00', 'YYYY-MM-DD HH24:MI:SS'),
        NULL,
        NULL,
        NULL);

INSERT INTO ORDER_REQUEST (STORE_ID, SUPPLIER_INTEGRATION_ID, PRODUCT_ID, REQUEST_EMPLOYEE_ID,
                           APPROVAL_EMPLOYEE_ID, APPROVAL_ROLE_ID, EXTERNAL_ORDER_ID,
                           ORDER_QUANTITY, APPROVED_QUANTITY, REQUEST_REASON, REJECT_REASON,
                           ORDER_STATUS, REQUESTED_AT, APPROVED_AT, REJECTED_AT, SENT_TO_SUPPLIER_AT)
VALUES ((SELECT STORE_ID FROM STORE WHERE STORE_NAME = 'SYSTEM 무역센터점'),
        (SELECT SUPPLIER_INTEGRATION_ID FROM SUPPLIER_INTEGRATION WHERE EXTERNAL_SUPPLIER_ID = '2'),
        (SELECT PRODUCT_ID FROM PRODUCT WHERE PRODUCT_NAME = 'SYSTEM 캐시미어 니트'),
        (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'store_system'),
        NULL,
        NULL,
        NULL,
        8,
        NULL,
        '안전재고 및 행사 대비 발주 요청',
        NULL,
        'REQUESTED',
        TO_DATE('2026-05-01 11:14:00', 'YYYY-MM-DD HH24:MI:SS'),
        NULL,
        NULL,
        NULL);

INSERT INTO ORDER_REQUEST (STORE_ID, SUPPLIER_INTEGRATION_ID, PRODUCT_ID, REQUEST_EMPLOYEE_ID,
                           APPROVAL_EMPLOYEE_ID, APPROVAL_ROLE_ID, EXTERNAL_ORDER_ID,
                           ORDER_QUANTITY, APPROVED_QUANTITY, REQUEST_REASON, REJECT_REASON,
                           ORDER_STATUS, REQUESTED_AT, APPROVED_AT, REJECTED_AT, SENT_TO_SUPPLIER_AT)
VALUES ((SELECT STORE_ID FROM STORE WHERE STORE_NAME = 'MINE 더현대서울점'),
        (SELECT SUPPLIER_INTEGRATION_ID FROM SUPPLIER_INTEGRATION WHERE EXTERNAL_SUPPLIER_ID = '3'),
        (SELECT PRODUCT_ID FROM PRODUCT WHERE PRODUCT_NAME = 'MINE 트렌치 코트'),
        (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'store_mine'),
        NULL,
        NULL,
        NULL,
        6,
        NULL,
        '안전재고 및 행사 대비 발주 요청',
        NULL,
        'REQUESTED',
        TO_DATE('2026-05-01 12:21:00', 'YYYY-MM-DD HH24:MI:SS'),
        NULL,
        NULL,
        NULL);

INSERT INTO ORDER_REQUEST (STORE_ID, SUPPLIER_INTEGRATION_ID, PRODUCT_ID, REQUEST_EMPLOYEE_ID,
                           APPROVAL_EMPLOYEE_ID, APPROVAL_ROLE_ID, EXTERNAL_ORDER_ID,
                           ORDER_QUANTITY, APPROVED_QUANTITY, REQUEST_REASON, REJECT_REASON,
                           ORDER_STATUS, REQUESTED_AT, APPROVED_AT, REJECTED_AT, SENT_TO_SUPPLIER_AT)
VALUES ((SELECT STORE_ID FROM STORE WHERE STORE_NAME = 'THE CASHMERE 더현대서울점'),
        (SELECT SUPPLIER_INTEGRATION_ID FROM SUPPLIER_INTEGRATION WHERE EXTERNAL_SUPPLIER_ID = '4'),
        (SELECT PRODUCT_ID FROM PRODUCT WHERE PRODUCT_NAME = 'THE CASHMERE 홀가먼트 니트'),
        (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'store_cashmere'),
        NULL,
        NULL,
        NULL,
        9,
        NULL,
        '안전재고 및 행사 대비 발주 요청',
        NULL,
        'REQUESTED',
        TO_DATE('2026-05-01 13:28:00', 'YYYY-MM-DD HH24:MI:SS'),
        NULL,
        NULL,
        NULL);

INSERT INTO ORDER_REQUEST (STORE_ID, SUPPLIER_INTEGRATION_ID, PRODUCT_ID, REQUEST_EMPLOYEE_ID,
                           APPROVAL_EMPLOYEE_ID, APPROVAL_ROLE_ID, EXTERNAL_ORDER_ID,
                           ORDER_QUANTITY, APPROVED_QUANTITY, REQUEST_REASON, REJECT_REASON,
                           ORDER_STATUS, REQUESTED_AT, APPROVED_AT, REJECTED_AT, SENT_TO_SUPPLIER_AT)
VALUES ((SELECT STORE_ID FROM STORE WHERE STORE_NAME = 'TIME 판교점'),
        (SELECT SUPPLIER_INTEGRATION_ID FROM SUPPLIER_INTEGRATION WHERE EXTERNAL_SUPPLIER_ID = '1'),
        (SELECT PRODUCT_ID FROM PRODUCT WHERE PRODUCT_NAME = 'TIME 울 블렌드 재킷'),
        (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'store_time'),
        (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'logi_time'),
        (SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = '발주처담당자'),
        '1005',
        20,
        20,
        '안전재고 및 행사 대비 발주 요청',
        NULL,
        'APPROVED',
        TO_DATE('2026-05-02 09:35:00', 'YYYY-MM-DD HH24:MI:SS'),
        TO_DATE('2026-05-02 13:55:00', 'YYYY-MM-DD HH24:MI:SS'),
        NULL,
        TO_DATE('2026-05-02 15:05:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO ORDER_REQUEST (STORE_ID, SUPPLIER_INTEGRATION_ID, PRODUCT_ID, REQUEST_EMPLOYEE_ID,
                           APPROVAL_EMPLOYEE_ID, APPROVAL_ROLE_ID, EXTERNAL_ORDER_ID,
                           ORDER_QUANTITY, APPROVED_QUANTITY, REQUEST_REASON, REJECT_REASON,
                           ORDER_STATUS, REQUESTED_AT, APPROVED_AT, REJECTED_AT, SENT_TO_SUPPLIER_AT)
VALUES ((SELECT STORE_ID FROM STORE WHERE STORE_NAME = 'TIME 판교점'),
        (SELECT SUPPLIER_INTEGRATION_ID FROM SUPPLIER_INTEGRATION WHERE EXTERNAL_SUPPLIER_ID = '1'),
        (SELECT PRODUCT_ID FROM PRODUCT WHERE PRODUCT_NAME = 'TIME 썸머 린넨 원피스'),
        (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'store_time'),
        (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'logi_time'),
        (SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = '발주처담당자'),
        '1006',
        15,
        12,
        '안전재고 및 행사 대비 발주 요청',
        NULL,
        'APPROVED',
        TO_DATE('2026-05-02 10:42:00', 'YYYY-MM-DD HH24:MI:SS'),
        TO_DATE('2026-05-02 14:06:00', 'YYYY-MM-DD HH24:MI:SS'),
        NULL,
        TO_DATE('2026-05-02 13:18:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO ORDER_REQUEST (STORE_ID, SUPPLIER_INTEGRATION_ID, PRODUCT_ID, REQUEST_EMPLOYEE_ID,
                           APPROVAL_EMPLOYEE_ID, APPROVAL_ROLE_ID, EXTERNAL_ORDER_ID,
                           ORDER_QUANTITY, APPROVED_QUANTITY, REQUEST_REASON, REJECT_REASON,
                           ORDER_STATUS, REQUESTED_AT, APPROVED_AT, REJECTED_AT, SENT_TO_SUPPLIER_AT)
VALUES ((SELECT STORE_ID FROM STORE WHERE STORE_NAME = 'SYSTEM 무역센터점'),
        (SELECT SUPPLIER_INTEGRATION_ID FROM SUPPLIER_INTEGRATION WHERE EXTERNAL_SUPPLIER_ID = '2'),
        (SELECT PRODUCT_ID FROM PRODUCT WHERE PRODUCT_NAME = 'SYSTEM 캐시미어 니트'),
        (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'store_system'),
        (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'logi_system'),
        (SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = '발주처담당자'),
        '1007',
        18,
        18,
        '안전재고 및 행사 대비 발주 요청',
        NULL,
        'APPROVED',
        TO_DATE('2026-05-02 11:49:00', 'YYYY-MM-DD HH24:MI:SS'),
        TO_DATE('2026-05-02 15:17:00', 'YYYY-MM-DD HH24:MI:SS'),
        NULL,
        TO_DATE('2026-05-02 14:31:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO ORDER_REQUEST (STORE_ID, SUPPLIER_INTEGRATION_ID, PRODUCT_ID, REQUEST_EMPLOYEE_ID,
                           APPROVAL_EMPLOYEE_ID, APPROVAL_ROLE_ID, EXTERNAL_ORDER_ID,
                           ORDER_QUANTITY, APPROVED_QUANTITY, REQUEST_REASON, REJECT_REASON,
                           ORDER_STATUS, REQUESTED_AT, APPROVED_AT, REJECTED_AT, SENT_TO_SUPPLIER_AT)
VALUES ((SELECT STORE_ID FROM STORE WHERE STORE_NAME = 'THE CASHMERE 더현대서울점'),
        (SELECT SUPPLIER_INTEGRATION_ID FROM SUPPLIER_INTEGRATION WHERE EXTERNAL_SUPPLIER_ID = '4'),
        (SELECT PRODUCT_ID FROM PRODUCT WHERE PRODUCT_NAME = 'THE CASHMERE 홀가먼트 니트'),
        (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'store_cashmere'),
        (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'logi_cashmere'),
        (SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = '발주처담당자'),
        '1008',
        12,
        10,
        '안전재고 및 행사 대비 발주 요청',
        NULL,
        'APPROVED',
        TO_DATE('2026-05-02 12:56:00', 'YYYY-MM-DD HH24:MI:SS'),
        TO_DATE('2026-05-02 12:28:00', 'YYYY-MM-DD HH24:MI:SS'),
        NULL,
        TO_DATE('2026-05-02 15:44:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO ORDER_REQUEST (STORE_ID, SUPPLIER_INTEGRATION_ID, PRODUCT_ID, REQUEST_EMPLOYEE_ID,
                           APPROVAL_EMPLOYEE_ID, APPROVAL_ROLE_ID, EXTERNAL_ORDER_ID,
                           ORDER_QUANTITY, APPROVED_QUANTITY, REQUEST_REASON, REJECT_REASON,
                           ORDER_STATUS, REQUESTED_AT, APPROVED_AT, REJECTED_AT, SENT_TO_SUPPLIER_AT)
VALUES ((SELECT STORE_ID FROM STORE WHERE STORE_NAME = 'TIME 판교점'),
        (SELECT SUPPLIER_INTEGRATION_ID FROM SUPPLIER_INTEGRATION WHERE EXTERNAL_SUPPLIER_ID = '1'),
        (SELECT PRODUCT_ID FROM PRODUCT WHERE PRODUCT_NAME = 'TIME 썸머 린넨 원피스'),
        (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'store_time'),
        (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'logi_time'),
        (SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = '발주처담당자'),
        NULL,
        30,
        NULL,
        '안전재고 및 행사 대비 발주 요청',
        '요청 수량 과다로 내부 반려',
        'REJECTED',
        TO_DATE('2026-05-03 13:03:00', 'YYYY-MM-DD HH24:MI:SS'),
        NULL,
        TO_DATE('2026-05-03 13:39:00', 'YYYY-MM-DD HH24:MI:SS'),
        NULL);

INSERT INTO ORDER_REQUEST (STORE_ID, SUPPLIER_INTEGRATION_ID, PRODUCT_ID, REQUEST_EMPLOYEE_ID,
                           APPROVAL_EMPLOYEE_ID, APPROVAL_ROLE_ID, EXTERNAL_ORDER_ID,
                           ORDER_QUANTITY, APPROVED_QUANTITY, REQUEST_REASON, REJECT_REASON,
                           ORDER_STATUS, REQUESTED_AT, APPROVED_AT, REJECTED_AT, SENT_TO_SUPPLIER_AT)
VALUES ((SELECT STORE_ID FROM STORE WHERE STORE_NAME = 'SYSTEM 무역센터점'),
        (SELECT SUPPLIER_INTEGRATION_ID FROM SUPPLIER_INTEGRATION WHERE EXTERNAL_SUPPLIER_ID = '2'),
        (SELECT PRODUCT_ID FROM PRODUCT WHERE PRODUCT_NAME = 'SYSTEM 캐시미어 니트'),
        (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'store_system'),
        (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'logi_system'),
        (SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = '발주처담당자'),
        NULL,
        25,
        NULL,
        '안전재고 및 행사 대비 발주 요청',
        '행사 계획 미확정으로 내부 반려',
        'REJECTED',
        TO_DATE('2026-05-03 09:10:00', 'YYYY-MM-DD HH24:MI:SS'),
        NULL,
        TO_DATE('2026-05-03 14:50:00', 'YYYY-MM-DD HH24:MI:SS'),
        NULL);

INSERT INTO ORDER_REQUEST (STORE_ID, SUPPLIER_INTEGRATION_ID, PRODUCT_ID, REQUEST_EMPLOYEE_ID,
                           APPROVAL_EMPLOYEE_ID, APPROVAL_ROLE_ID, EXTERNAL_ORDER_ID,
                           ORDER_QUANTITY, APPROVED_QUANTITY, REQUEST_REASON, REJECT_REASON,
                           ORDER_STATUS, REQUESTED_AT, APPROVED_AT, REJECTED_AT, SENT_TO_SUPPLIER_AT)
VALUES ((SELECT STORE_ID FROM STORE WHERE STORE_NAME = 'MINE 더현대서울점'),
        (SELECT SUPPLIER_INTEGRATION_ID FROM SUPPLIER_INTEGRATION WHERE EXTERNAL_SUPPLIER_ID = '3'),
        (SELECT PRODUCT_ID FROM PRODUCT WHERE PRODUCT_NAME = 'MINE 트렌치 코트'),
        (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'store_mine'),
        (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'logi_mine'),
        (SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = '발주처담당자'),
        NULL,
        14,
        NULL,
        '안전재고 및 행사 대비 발주 요청',
        '최근 판매량 대비 과다 요청',
        'REJECTED',
        TO_DATE('2026-05-03 10:17:00', 'YYYY-MM-DD HH24:MI:SS'),
        NULL,
        TO_DATE('2026-05-03 15:01:00', 'YYYY-MM-DD HH24:MI:SS'),
        NULL);

INSERT INTO ORDER_REQUEST (STORE_ID, SUPPLIER_INTEGRATION_ID, PRODUCT_ID, REQUEST_EMPLOYEE_ID,
                           APPROVAL_EMPLOYEE_ID, APPROVAL_ROLE_ID, EXTERNAL_ORDER_ID,
                           ORDER_QUANTITY, APPROVED_QUANTITY, REQUEST_REASON, REJECT_REASON,
                           ORDER_STATUS, REQUESTED_AT, APPROVED_AT, REJECTED_AT, SENT_TO_SUPPLIER_AT)
VALUES ((SELECT STORE_ID FROM STORE WHERE STORE_NAME = 'THE CASHMERE 더현대서울점'),
        (SELECT SUPPLIER_INTEGRATION_ID FROM SUPPLIER_INTEGRATION WHERE EXTERNAL_SUPPLIER_ID = '4'),
        (SELECT PRODUCT_ID FROM PRODUCT WHERE PRODUCT_NAME = 'THE CASHMERE 홀가먼트 니트'),
        (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'store_cashmere'),
        (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'logi_cashmere'),
        (SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = '발주처담당자'),
        NULL,
        16,
        NULL,
        '안전재고 및 행사 대비 발주 요청',
        '안전재고 이상으로 내부 반려',
        'REJECTED',
        TO_DATE('2026-05-03 11:24:00', 'YYYY-MM-DD HH24:MI:SS'),
        NULL,
        TO_DATE('2026-05-03 12:12:00', 'YYYY-MM-DD HH24:MI:SS'),
        NULL);

INSERT INTO ORDER_REQUEST (STORE_ID, SUPPLIER_INTEGRATION_ID, PRODUCT_ID, REQUEST_EMPLOYEE_ID,
                           APPROVAL_EMPLOYEE_ID, APPROVAL_ROLE_ID, EXTERNAL_ORDER_ID,
                           ORDER_QUANTITY, APPROVED_QUANTITY, REQUEST_REASON, REJECT_REASON,
                           ORDER_STATUS, REQUESTED_AT, APPROVED_AT, REJECTED_AT, SENT_TO_SUPPLIER_AT)
VALUES ((SELECT STORE_ID FROM STORE WHERE STORE_NAME = 'TIME 판교점'),
        (SELECT SUPPLIER_INTEGRATION_ID FROM SUPPLIER_INTEGRATION WHERE EXTERNAL_SUPPLIER_ID = '1'),
        (SELECT PRODUCT_ID FROM PRODUCT WHERE PRODUCT_NAME = 'TIME 울 블렌드 재킷'),
        (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'store_time'),
        (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'logi_time'),
        (SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = '발주처담당자'),
        '1013',
        10,
        10,
        '안전재고 및 행사 대비 발주 요청',
        NULL,
        'RECEIVED',
        TO_DATE('2026-05-04 12:31:00', 'YYYY-MM-DD HH24:MI:SS'),
        TO_DATE('2026-05-04 13:23:00', 'YYYY-MM-DD HH24:MI:SS'),
        NULL,
        TO_DATE('2026-05-04 14:49:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO ORDER_REQUEST (STORE_ID, SUPPLIER_INTEGRATION_ID, PRODUCT_ID, REQUEST_EMPLOYEE_ID,
                           APPROVAL_EMPLOYEE_ID, APPROVAL_ROLE_ID, EXTERNAL_ORDER_ID,
                           ORDER_QUANTITY, APPROVED_QUANTITY, REQUEST_REASON, REJECT_REASON,
                           ORDER_STATUS, REQUESTED_AT, APPROVED_AT, REJECTED_AT, SENT_TO_SUPPLIER_AT)
VALUES ((SELECT STORE_ID FROM STORE WHERE STORE_NAME = 'TIME 판교점'),
        (SELECT SUPPLIER_INTEGRATION_ID FROM SUPPLIER_INTEGRATION WHERE EXTERNAL_SUPPLIER_ID = '1'),
        (SELECT PRODUCT_ID FROM PRODUCT WHERE PRODUCT_NAME = 'TIME 썸머 린넨 원피스'),
        (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'store_time'),
        (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'logi_time'),
        (SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = '발주처담당자'),
        '1014',
        11,
        9,
        '안전재고 및 행사 대비 발주 요청',
        NULL,
        'RECEIVED',
        TO_DATE('2026-05-04 13:38:00', 'YYYY-MM-DD HH24:MI:SS'),
        TO_DATE('2026-05-04 14:34:00', 'YYYY-MM-DD HH24:MI:SS'),
        NULL,
        TO_DATE('2026-05-04 15:02:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO ORDER_REQUEST (STORE_ID, SUPPLIER_INTEGRATION_ID, PRODUCT_ID, REQUEST_EMPLOYEE_ID,
                           APPROVAL_EMPLOYEE_ID, APPROVAL_ROLE_ID, EXTERNAL_ORDER_ID,
                           ORDER_QUANTITY, APPROVED_QUANTITY, REQUEST_REASON, REJECT_REASON,
                           ORDER_STATUS, REQUESTED_AT, APPROVED_AT, REJECTED_AT, SENT_TO_SUPPLIER_AT)
VALUES ((SELECT STORE_ID FROM STORE WHERE STORE_NAME = 'SYSTEM 무역센터점'),
        (SELECT SUPPLIER_INTEGRATION_ID FROM SUPPLIER_INTEGRATION WHERE EXTERNAL_SUPPLIER_ID = '2'),
        (SELECT PRODUCT_ID FROM PRODUCT WHERE PRODUCT_NAME = 'SYSTEM 캐시미어 니트'),
        (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'store_system'),
        (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'logi_system'),
        (SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = '발주처담당자'),
        '1015',
        7,
        7,
        '안전재고 및 행사 대비 발주 요청',
        NULL,
        'RECEIVED',
        TO_DATE('2026-05-04 09:45:00', 'YYYY-MM-DD HH24:MI:SS'),
        TO_DATE('2026-05-04 15:45:00', 'YYYY-MM-DD HH24:MI:SS'),
        NULL,
        TO_DATE('2026-05-04 13:15:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO ORDER_REQUEST (STORE_ID, SUPPLIER_INTEGRATION_ID, PRODUCT_ID, REQUEST_EMPLOYEE_ID,
                           APPROVAL_EMPLOYEE_ID, APPROVAL_ROLE_ID, EXTERNAL_ORDER_ID,
                           ORDER_QUANTITY, APPROVED_QUANTITY, REQUEST_REASON, REJECT_REASON,
                           ORDER_STATUS, REQUESTED_AT, APPROVED_AT, REJECTED_AT, SENT_TO_SUPPLIER_AT)
VALUES ((SELECT STORE_ID FROM STORE WHERE STORE_NAME = 'MINE 더현대서울점'),
        (SELECT SUPPLIER_INTEGRATION_ID FROM SUPPLIER_INTEGRATION WHERE EXTERNAL_SUPPLIER_ID = '3'),
        (SELECT PRODUCT_ID FROM PRODUCT WHERE PRODUCT_NAME = 'MINE 트렌치 코트'),
        (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'store_mine'),
        (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'logi_mine'),
        (SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = '발주처담당자'),
        '1016',
        5,
        5,
        '안전재고 및 행사 대비 발주 요청',
        NULL,
        'RECEIVED',
        TO_DATE('2026-05-04 10:52:00', 'YYYY-MM-DD HH24:MI:SS'),
        TO_DATE('2026-05-04 12:56:00', 'YYYY-MM-DD HH24:MI:SS'),
        NULL,
        TO_DATE('2026-05-04 14:28:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO ORDER_REQUEST (STORE_ID, SUPPLIER_INTEGRATION_ID, PRODUCT_ID, REQUEST_EMPLOYEE_ID,
                           APPROVAL_EMPLOYEE_ID, APPROVAL_ROLE_ID, EXTERNAL_ORDER_ID,
                           ORDER_QUANTITY, APPROVED_QUANTITY, REQUEST_REASON, REJECT_REASON,
                           ORDER_STATUS, REQUESTED_AT, APPROVED_AT, REJECTED_AT, SENT_TO_SUPPLIER_AT)
VALUES ((SELECT STORE_ID FROM STORE WHERE STORE_NAME = 'TIME 판교점'),
        (SELECT SUPPLIER_INTEGRATION_ID FROM SUPPLIER_INTEGRATION WHERE EXTERNAL_SUPPLIER_ID = '1'),
        (SELECT PRODUCT_ID FROM PRODUCT WHERE PRODUCT_NAME = 'TIME 썸머 린넨 원피스'),
        (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'store_time'),
        (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'logi_time'),
        (SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = '발주처담당자'),
        '1017',
        13,
        13,
        '안전재고 및 행사 대비 발주 요청',
        '외부 공급사 품절로 취소',
        'CANCELED',
        TO_DATE('2026-05-05 11:59:00', 'YYYY-MM-DD HH24:MI:SS'),
        NULL,
        TO_DATE('2026-05-05 13:07:00', 'YYYY-MM-DD HH24:MI:SS'),
        TO_DATE('2026-05-05 15:41:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO ORDER_REQUEST (STORE_ID, SUPPLIER_INTEGRATION_ID, PRODUCT_ID, REQUEST_EMPLOYEE_ID,
                           APPROVAL_EMPLOYEE_ID, APPROVAL_ROLE_ID, EXTERNAL_ORDER_ID,
                           ORDER_QUANTITY, APPROVED_QUANTITY, REQUEST_REASON, REJECT_REASON,
                           ORDER_STATUS, REQUESTED_AT, APPROVED_AT, REJECTED_AT, SENT_TO_SUPPLIER_AT)
VALUES ((SELECT STORE_ID FROM STORE WHERE STORE_NAME = 'SYSTEM 무역센터점'),
        (SELECT SUPPLIER_INTEGRATION_ID FROM SUPPLIER_INTEGRATION WHERE EXTERNAL_SUPPLIER_ID = '2'),
        (SELECT PRODUCT_ID FROM PRODUCT WHERE PRODUCT_NAME = 'SYSTEM 캐시미어 니트'),
        (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'store_system'),
        (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'logi_system'),
        (SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = '발주처담당자'),
        '1018',
        9,
        9,
        '안전재고 및 행사 대비 발주 요청',
        '외부 공급사 출고 불가로 취소',
        'CANCELED',
        TO_DATE('2026-05-05 12:06:00', 'YYYY-MM-DD HH24:MI:SS'),
        NULL,
        TO_DATE('2026-05-05 14:18:00', 'YYYY-MM-DD HH24:MI:SS'),
        TO_DATE('2026-05-05 13:54:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO ORDER_REQUEST (STORE_ID, SUPPLIER_INTEGRATION_ID, PRODUCT_ID, REQUEST_EMPLOYEE_ID,
                           APPROVAL_EMPLOYEE_ID, APPROVAL_ROLE_ID, EXTERNAL_ORDER_ID,
                           ORDER_QUANTITY, APPROVED_QUANTITY, REQUEST_REASON, REJECT_REASON,
                           ORDER_STATUS, REQUESTED_AT, APPROVED_AT, REJECTED_AT, SENT_TO_SUPPLIER_AT)
VALUES ((SELECT STORE_ID FROM STORE WHERE STORE_NAME = 'MINE 더현대서울점'),
        (SELECT SUPPLIER_INTEGRATION_ID FROM SUPPLIER_INTEGRATION WHERE EXTERNAL_SUPPLIER_ID = '3'),
        (SELECT PRODUCT_ID FROM PRODUCT WHERE PRODUCT_NAME = 'MINE 트렌치 코트'),
        (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'store_mine'),
        (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'logi_mine'),
        (SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = '발주처담당자'),
        '1019',
        8,
        8,
        '안전재고 및 행사 대비 발주 요청',
        '외부 공급사 재고 오류로 취소',
        'CANCELED',
        TO_DATE('2026-05-05 13:13:00', 'YYYY-MM-DD HH24:MI:SS'),
        NULL,
        TO_DATE('2026-05-05 15:29:00', 'YYYY-MM-DD HH24:MI:SS'),
        TO_DATE('2026-05-05 14:07:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO ORDER_REQUEST (STORE_ID, SUPPLIER_INTEGRATION_ID, PRODUCT_ID, REQUEST_EMPLOYEE_ID,
                           APPROVAL_EMPLOYEE_ID, APPROVAL_ROLE_ID, EXTERNAL_ORDER_ID,
                           ORDER_QUANTITY, APPROVED_QUANTITY, REQUEST_REASON, REJECT_REASON,
                           ORDER_STATUS, REQUESTED_AT, APPROVED_AT, REJECTED_AT, SENT_TO_SUPPLIER_AT)
VALUES ((SELECT STORE_ID FROM STORE WHERE STORE_NAME = 'TIME 판교점'),
        (SELECT SUPPLIER_INTEGRATION_ID FROM SUPPLIER_INTEGRATION WHERE EXTERNAL_SUPPLIER_ID = '1'),
        (SELECT PRODUCT_ID FROM PRODUCT WHERE PRODUCT_NAME = 'TIME 울 블렌드 재킷'),
        (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'store_time'),
        (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'logi_time'),
        (SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = '발주처담당자'),
        '1020',
        16,
        16,
        '안전재고 및 행사 대비 발주 요청',
        NULL,
        'DONE',
        TO_DATE('2026-05-05 09:20:00', 'YYYY-MM-DD HH24:MI:SS'),
        TO_DATE('2026-05-05 12:40:00', 'YYYY-MM-DD HH24:MI:SS'),
        NULL,
        TO_DATE('2026-05-05 15:20:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO ORDER_REQUEST (STORE_ID, SUPPLIER_INTEGRATION_ID, PRODUCT_ID, REQUEST_EMPLOYEE_ID,
                           APPROVAL_EMPLOYEE_ID, APPROVAL_ROLE_ID, EXTERNAL_ORDER_ID,
                           ORDER_QUANTITY, APPROVED_QUANTITY, REQUEST_REASON, REJECT_REASON,
                           ORDER_STATUS, REQUESTED_AT, APPROVED_AT, REJECTED_AT, SENT_TO_SUPPLIER_AT)
VALUES ((SELECT STORE_ID FROM STORE WHERE STORE_NAME = 'SYSTEM 무역센터점'),
        (SELECT SUPPLIER_INTEGRATION_ID FROM SUPPLIER_INTEGRATION WHERE EXTERNAL_SUPPLIER_ID = '2'),
        (SELECT PRODUCT_ID FROM PRODUCT WHERE PRODUCT_NAME = 'SYSTEM 캐시미어 니트'),
        (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'store_system'),
        (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'logi_system'),
        (SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = '발주처담당자'),
        '1021',
        10,
        10,
        '안전재고 및 행사 대비 발주 요청',
        NULL,
        'DONE',
        TO_DATE('2026-05-06 10:27:00', 'YYYY-MM-DD HH24:MI:SS'),
        TO_DATE('2026-05-06 13:51:00', 'YYYY-MM-DD HH24:MI:SS'),
        NULL,
        TO_DATE('2026-05-06 13:33:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO ORDER_REQUEST (STORE_ID, SUPPLIER_INTEGRATION_ID, PRODUCT_ID, REQUEST_EMPLOYEE_ID,
                           APPROVAL_EMPLOYEE_ID, APPROVAL_ROLE_ID, EXTERNAL_ORDER_ID,
                           ORDER_QUANTITY, APPROVED_QUANTITY, REQUEST_REASON, REJECT_REASON,
                           ORDER_STATUS, REQUESTED_AT, APPROVED_AT, REJECTED_AT, SENT_TO_SUPPLIER_AT)
VALUES ((SELECT STORE_ID FROM STORE WHERE STORE_NAME = 'THE CASHMERE 더현대서울점'),
        (SELECT SUPPLIER_INTEGRATION_ID FROM SUPPLIER_INTEGRATION WHERE EXTERNAL_SUPPLIER_ID = '4'),
        (SELECT PRODUCT_ID FROM PRODUCT WHERE PRODUCT_NAME = 'THE CASHMERE 홀가먼트 니트'),
        (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'store_cashmere'),
        (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'logi_cashmere'),
        (SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = '발주처담당자'),
        '1022',
        6,
        6,
        '안전재고 및 행사 대비 발주 요청',
        NULL,
        'DONE',
        TO_DATE('2026-05-06 11:34:00', 'YYYY-MM-DD HH24:MI:SS'),
        TO_DATE('2026-05-06 14:02:00', 'YYYY-MM-DD HH24:MI:SS'),
        NULL,
        TO_DATE('2026-05-06 14:46:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO ORDER_REQUEST (STORE_ID, SUPPLIER_INTEGRATION_ID, PRODUCT_ID, REQUEST_EMPLOYEE_ID,
                           APPROVAL_EMPLOYEE_ID, APPROVAL_ROLE_ID, EXTERNAL_ORDER_ID,
                           ORDER_QUANTITY, APPROVED_QUANTITY, REQUEST_REASON, REJECT_REASON,
                           ORDER_STATUS, REQUESTED_AT, APPROVED_AT, REJECTED_AT, SENT_TO_SUPPLIER_AT)
VALUES ((SELECT STORE_ID FROM STORE WHERE STORE_NAME = 'TIME 판교점'),
        (SELECT SUPPLIER_INTEGRATION_ID FROM SUPPLIER_INTEGRATION WHERE EXTERNAL_SUPPLIER_ID = '1'),
        (SELECT PRODUCT_ID FROM PRODUCT WHERE PRODUCT_NAME = 'TIME 썸머 린넨 원피스'),
        (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'store_time'),
        (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'logi_time'),
        (SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = '발주처담당자'),
        '1023',
        12,
        12,
        '안전재고 및 행사 대비 발주 요청',
        NULL,
        'DONE',
        TO_DATE('2026-05-06 12:41:00', 'YYYY-MM-DD HH24:MI:SS'),
        TO_DATE('2026-05-06 15:13:00', 'YYYY-MM-DD HH24:MI:SS'),
        NULL,
        TO_DATE('2026-05-06 15:59:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO ORDER_REQUEST (STORE_ID, SUPPLIER_INTEGRATION_ID, PRODUCT_ID, REQUEST_EMPLOYEE_ID,
                           APPROVAL_EMPLOYEE_ID, APPROVAL_ROLE_ID, EXTERNAL_ORDER_ID,
                           ORDER_QUANTITY, APPROVED_QUANTITY, REQUEST_REASON, REJECT_REASON,
                           ORDER_STATUS, REQUESTED_AT, APPROVED_AT, REJECTED_AT, SENT_TO_SUPPLIER_AT)
VALUES ((SELECT STORE_ID FROM STORE WHERE STORE_NAME = 'SYSTEM 무역센터점'),
        (SELECT SUPPLIER_INTEGRATION_ID FROM SUPPLIER_INTEGRATION WHERE EXTERNAL_SUPPLIER_ID = '2'),
        (SELECT PRODUCT_ID FROM PRODUCT WHERE PRODUCT_NAME = 'SYSTEM 캐시미어 니트'),
        (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'store_system'),
        (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'logi_system'),
        (SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = '발주처담당자'),
        '1024',
        15,
        15,
        '안전재고 및 행사 대비 발주 요청',
        NULL,
        'DONE',
        TO_DATE('2026-05-06 13:48:00', 'YYYY-MM-DD HH24:MI:SS'),
        TO_DATE('2026-05-06 12:24:00', 'YYYY-MM-DD HH24:MI:SS'),
        NULL,
        TO_DATE('2026-05-06 13:12:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO ORDER_REQUEST (STORE_ID, SUPPLIER_INTEGRATION_ID, PRODUCT_ID, REQUEST_EMPLOYEE_ID,
                           APPROVAL_EMPLOYEE_ID, APPROVAL_ROLE_ID, EXTERNAL_ORDER_ID,
                           ORDER_QUANTITY, APPROVED_QUANTITY, REQUEST_REASON, REJECT_REASON,
                           ORDER_STATUS, REQUESTED_AT, APPROVED_AT, REJECTED_AT, SENT_TO_SUPPLIER_AT)
VALUES ((SELECT STORE_ID FROM STORE WHERE STORE_NAME = 'MINE 더현대서울점'),
        (SELECT SUPPLIER_INTEGRATION_ID FROM SUPPLIER_INTEGRATION WHERE EXTERNAL_SUPPLIER_ID = '3'),
        (SELECT PRODUCT_ID FROM PRODUCT WHERE PRODUCT_NAME = 'MINE 트렌치 코트'),
        (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'store_mine'),
        (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'logi_mine'),
        (SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = '발주처담당자'),
        '1025',
        9,
        9,
        '안전재고 및 행사 대비 발주 요청',
        NULL,
        'DONE',
        TO_DATE('2026-05-07 09:55:00', 'YYYY-MM-DD HH24:MI:SS'),
        TO_DATE('2026-05-07 13:35:00', 'YYYY-MM-DD HH24:MI:SS'),
        NULL,
        TO_DATE('2026-05-07 14:25:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO ORDER_REQUEST (STORE_ID, SUPPLIER_INTEGRATION_ID, PRODUCT_ID, REQUEST_EMPLOYEE_ID,
                           APPROVAL_EMPLOYEE_ID, APPROVAL_ROLE_ID, EXTERNAL_ORDER_ID,
                           ORDER_QUANTITY, APPROVED_QUANTITY, REQUEST_REASON, REJECT_REASON,
                           ORDER_STATUS, REQUESTED_AT, APPROVED_AT, REJECTED_AT, SENT_TO_SUPPLIER_AT)
VALUES ((SELECT STORE_ID FROM STORE WHERE STORE_NAME = 'TIME 판교점'),
        (SELECT SUPPLIER_INTEGRATION_ID FROM SUPPLIER_INTEGRATION WHERE EXTERNAL_SUPPLIER_ID = '1'),
        (SELECT PRODUCT_ID FROM PRODUCT WHERE PRODUCT_NAME = 'TIME 울 블렌드 재킷'),
        (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'store_time'),
        (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'logi_time'),
        (SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = '발주처담당자'),
        '1026',
        5,
        5,
        '안전재고 및 행사 대비 발주 요청',
        NULL,
        'DONE',
        TO_DATE('2026-05-07 10:02:00', 'YYYY-MM-DD HH24:MI:SS'),
        TO_DATE('2026-05-07 14:46:00', 'YYYY-MM-DD HH24:MI:SS'),
        NULL,
        TO_DATE('2026-05-07 15:38:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO ORDER_REQUEST (STORE_ID, SUPPLIER_INTEGRATION_ID, PRODUCT_ID, REQUEST_EMPLOYEE_ID,
                           APPROVAL_EMPLOYEE_ID, APPROVAL_ROLE_ID, EXTERNAL_ORDER_ID,
                           ORDER_QUANTITY, APPROVED_QUANTITY, REQUEST_REASON, REJECT_REASON,
                           ORDER_STATUS, REQUESTED_AT, APPROVED_AT, REJECTED_AT, SENT_TO_SUPPLIER_AT)
VALUES ((SELECT STORE_ID FROM STORE WHERE STORE_NAME = 'MINE 더현대서울점'),
        (SELECT SUPPLIER_INTEGRATION_ID FROM SUPPLIER_INTEGRATION WHERE EXTERNAL_SUPPLIER_ID = '3'),
        (SELECT PRODUCT_ID FROM PRODUCT WHERE PRODUCT_NAME = 'MINE 트렌치 코트'),
        (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'store_mine'),
        (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'logi_mine'),
        (SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = '발주처담당자'),
        '1027',
        4,
        4,
        '안전재고 및 행사 대비 발주 요청',
        NULL,
        'DONE',
        TO_DATE('2026-05-07 11:09:00', 'YYYY-MM-DD HH24:MI:SS'),
        TO_DATE('2026-05-07 15:57:00', 'YYYY-MM-DD HH24:MI:SS'),
        NULL,
        TO_DATE('2026-05-07 13:51:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO ORDER_REQUEST (STORE_ID, SUPPLIER_INTEGRATION_ID, PRODUCT_ID, REQUEST_EMPLOYEE_ID,
                           APPROVAL_EMPLOYEE_ID, APPROVAL_ROLE_ID, EXTERNAL_ORDER_ID,
                           ORDER_QUANTITY, APPROVED_QUANTITY, REQUEST_REASON, REJECT_REASON,
                           ORDER_STATUS, REQUESTED_AT, APPROVED_AT, REJECTED_AT, SENT_TO_SUPPLIER_AT)
VALUES ((SELECT STORE_ID FROM STORE WHERE STORE_NAME = 'THE CASHMERE 더현대서울점'),
        (SELECT SUPPLIER_INTEGRATION_ID FROM SUPPLIER_INTEGRATION WHERE EXTERNAL_SUPPLIER_ID = '4'),
        (SELECT PRODUCT_ID FROM PRODUCT WHERE PRODUCT_NAME = 'THE CASHMERE 홀가먼트 니트'),
        (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'store_cashmere'),
        (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'logi_cashmere'),
        (SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = '발주처담당자'),
        '1028',
        7,
        7,
        '안전재고 및 행사 대비 발주 요청',
        NULL,
        'DONE',
        TO_DATE('2026-05-07 12:16:00', 'YYYY-MM-DD HH24:MI:SS'),
        TO_DATE('2026-05-07 12:08:00', 'YYYY-MM-DD HH24:MI:SS'),
        NULL,
        TO_DATE('2026-05-07 14:04:00', 'YYYY-MM-DD HH24:MI:SS'));

/* ORDER_APPROVAL - 내부 승인/거절 및 외부 거절 반영 */

INSERT INTO ORDER_APPROVAL (APPROVAL_EMPLOYEE_ID, ORDER_REQUEST_ID, APPROVED_QUANTITY, APPROVAL_STATUS, APPROVAL_COMMENT, CREATED_AT)
VALUES ((SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'logi_time'),
        5,
        20,
        'APPROVED',
        '요청 20개 중 20개 승인',
        TO_DATE('2026-05-02 13:55:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO ORDER_APPROVAL (APPROVAL_EMPLOYEE_ID, ORDER_REQUEST_ID, APPROVED_QUANTITY, APPROVAL_STATUS, APPROVAL_COMMENT, CREATED_AT)
VALUES ((SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'logi_time'),
        6,
        12,
        'APPROVED',
        '요청 15개 중 12개 승인',
        TO_DATE('2026-05-02 14:06:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO ORDER_APPROVAL (APPROVAL_EMPLOYEE_ID, ORDER_REQUEST_ID, APPROVED_QUANTITY, APPROVAL_STATUS, APPROVAL_COMMENT, CREATED_AT)
VALUES ((SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'logi_system'),
        7,
        18,
        'APPROVED',
        '요청 18개 중 18개 승인',
        TO_DATE('2026-05-02 15:17:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO ORDER_APPROVAL (APPROVAL_EMPLOYEE_ID, ORDER_REQUEST_ID, APPROVED_QUANTITY, APPROVAL_STATUS, APPROVAL_COMMENT, CREATED_AT)
VALUES ((SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'logi_cashmere'),
        8,
        10,
        'APPROVED',
        '요청 12개 중 10개 승인',
        TO_DATE('2026-05-02 12:28:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO ORDER_APPROVAL (APPROVAL_EMPLOYEE_ID, ORDER_REQUEST_ID, APPROVED_QUANTITY, APPROVAL_STATUS, APPROVAL_COMMENT, CREATED_AT)
VALUES ((SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'logi_time'),
        9,
        NULL,
        'REJECTED',
        '요청 수량 과다로 내부 반려',
        TO_DATE('2026-05-03 13:39:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO ORDER_APPROVAL (APPROVAL_EMPLOYEE_ID, ORDER_REQUEST_ID, APPROVED_QUANTITY, APPROVAL_STATUS, APPROVAL_COMMENT, CREATED_AT)
VALUES ((SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'logi_system'),
        10,
        NULL,
        'REJECTED',
        '행사 계획 미확정으로 내부 반려',
        TO_DATE('2026-05-03 14:50:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO ORDER_APPROVAL (APPROVAL_EMPLOYEE_ID, ORDER_REQUEST_ID, APPROVED_QUANTITY, APPROVAL_STATUS, APPROVAL_COMMENT, CREATED_AT)
VALUES ((SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'logi_mine'),
        11,
        NULL,
        'REJECTED',
        '최근 판매량 대비 과다 요청',
        TO_DATE('2026-05-03 15:01:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO ORDER_APPROVAL (APPROVAL_EMPLOYEE_ID, ORDER_REQUEST_ID, APPROVED_QUANTITY, APPROVAL_STATUS, APPROVAL_COMMENT, CREATED_AT)
VALUES ((SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'logi_cashmere'),
        12,
        NULL,
        'REJECTED',
        '안전재고 이상으로 내부 반려',
        TO_DATE('2026-05-03 12:12:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO ORDER_APPROVAL (APPROVAL_EMPLOYEE_ID, ORDER_REQUEST_ID, APPROVED_QUANTITY, APPROVAL_STATUS, APPROVAL_COMMENT, CREATED_AT)
VALUES ((SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'logi_time'),
        13,
        10,
        'APPROVED',
        '요청 10개 중 10개 승인',
        TO_DATE('2026-05-04 13:23:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO ORDER_APPROVAL (APPROVAL_EMPLOYEE_ID, ORDER_REQUEST_ID, APPROVED_QUANTITY, APPROVAL_STATUS, APPROVAL_COMMENT, CREATED_AT)
VALUES ((SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'logi_time'),
        14,
        9,
        'APPROVED',
        '요청 11개 중 9개 승인',
        TO_DATE('2026-05-04 14:34:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO ORDER_APPROVAL (APPROVAL_EMPLOYEE_ID, ORDER_REQUEST_ID, APPROVED_QUANTITY, APPROVAL_STATUS, APPROVAL_COMMENT, CREATED_AT)
VALUES ((SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'logi_system'),
        15,
        7,
        'APPROVED',
        '요청 7개 중 7개 승인',
        TO_DATE('2026-05-04 15:45:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO ORDER_APPROVAL (APPROVAL_EMPLOYEE_ID, ORDER_REQUEST_ID, APPROVED_QUANTITY, APPROVAL_STATUS, APPROVAL_COMMENT, CREATED_AT)
VALUES ((SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'logi_mine'),
        16,
        5,
        'APPROVED',
        '요청 5개 중 5개 승인',
        TO_DATE('2026-05-04 12:56:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO ORDER_APPROVAL (APPROVAL_EMPLOYEE_ID, ORDER_REQUEST_ID, APPROVED_QUANTITY, APPROVAL_STATUS, APPROVAL_COMMENT, CREATED_AT)
VALUES ((SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'logi_time'),
        17,
        NULL,
        'CANCELED',
        '외부 공급사 품절로 취소',
        TO_DATE('2026-05-05 13:07:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO ORDER_APPROVAL (APPROVAL_EMPLOYEE_ID, ORDER_REQUEST_ID, APPROVED_QUANTITY, APPROVAL_STATUS, APPROVAL_COMMENT, CREATED_AT)
VALUES ((SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'logi_system'),
        18,
        NULL,
        'CANCELED',
        '외부 공급사 출고 불가로 취소',
        TO_DATE('2026-05-05 14:18:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO ORDER_APPROVAL (APPROVAL_EMPLOYEE_ID, ORDER_REQUEST_ID, APPROVED_QUANTITY, APPROVAL_STATUS, APPROVAL_COMMENT, CREATED_AT)
VALUES ((SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'logi_mine'),
        19,
        NULL,
        'CANCELED',
        '외부 공급사 재고 오류로 취소',
        TO_DATE('2026-05-05 15:29:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO ORDER_APPROVAL (APPROVAL_EMPLOYEE_ID, ORDER_REQUEST_ID, APPROVED_QUANTITY, APPROVAL_STATUS, APPROVAL_COMMENT, CREATED_AT)
VALUES ((SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'logi_time'),
        20,
        16,
        'APPROVED',
        '요청 16개 중 16개 승인',
        TO_DATE('2026-05-05 12:40:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO ORDER_APPROVAL (APPROVAL_EMPLOYEE_ID, ORDER_REQUEST_ID, APPROVED_QUANTITY, APPROVAL_STATUS, APPROVAL_COMMENT, CREATED_AT)
VALUES ((SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'logi_system'),
        21,
        10,
        'APPROVED',
        '요청 10개 중 10개 승인',
        TO_DATE('2026-05-06 13:51:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO ORDER_APPROVAL (APPROVAL_EMPLOYEE_ID, ORDER_REQUEST_ID, APPROVED_QUANTITY, APPROVAL_STATUS, APPROVAL_COMMENT, CREATED_AT)
VALUES ((SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'logi_cashmere'),
        22,
        6,
        'APPROVED',
        '요청 6개 중 6개 승인',
        TO_DATE('2026-05-06 14:02:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO ORDER_APPROVAL (APPROVAL_EMPLOYEE_ID, ORDER_REQUEST_ID, APPROVED_QUANTITY, APPROVAL_STATUS, APPROVAL_COMMENT, CREATED_AT)
VALUES ((SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'logi_time'),
        23,
        12,
        'APPROVED',
        '요청 12개 중 12개 승인',
        TO_DATE('2026-05-06 15:13:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO ORDER_APPROVAL (APPROVAL_EMPLOYEE_ID, ORDER_REQUEST_ID, APPROVED_QUANTITY, APPROVAL_STATUS, APPROVAL_COMMENT, CREATED_AT)
VALUES ((SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'logi_system'),
        24,
        15,
        'APPROVED',
        '요청 15개 중 15개 승인',
        TO_DATE('2026-05-06 12:24:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO ORDER_APPROVAL (APPROVAL_EMPLOYEE_ID, ORDER_REQUEST_ID, APPROVED_QUANTITY, APPROVAL_STATUS, APPROVAL_COMMENT, CREATED_AT)
VALUES ((SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'logi_mine'),
        25,
        9,
        'APPROVED',
        '요청 9개 중 9개 승인',
        TO_DATE('2026-05-07 13:35:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO ORDER_APPROVAL (APPROVAL_EMPLOYEE_ID, ORDER_REQUEST_ID, APPROVED_QUANTITY, APPROVAL_STATUS, APPROVAL_COMMENT, CREATED_AT)
VALUES ((SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'logi_time'),
        26,
        5,
        'APPROVED',
        '요청 5개 중 5개 승인',
        TO_DATE('2026-05-07 14:46:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO ORDER_APPROVAL (APPROVAL_EMPLOYEE_ID, ORDER_REQUEST_ID, APPROVED_QUANTITY, APPROVAL_STATUS, APPROVAL_COMMENT, CREATED_AT)
VALUES ((SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'logi_mine'),
        27,
        4,
        'APPROVED',
        '요청 4개 중 4개 승인',
        TO_DATE('2026-05-07 15:57:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO ORDER_APPROVAL (APPROVAL_EMPLOYEE_ID, ORDER_REQUEST_ID, APPROVED_QUANTITY, APPROVAL_STATUS, APPROVAL_COMMENT, CREATED_AT)
VALUES ((SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'logi_cashmere'),
        28,
        7,
        'APPROVED',
        '요청 7개 중 7개 승인',
        TO_DATE('2026-05-07 12:08:00', 'YYYY-MM-DD HH24:MI:SS'));

/* STORE_RECEIPT - 매장 입고 확인/부분입고/입고취소 */

INSERT INTO STORE_RECEIPT (ORDER_REQUEST_ID, CONFIRM_EMPLOYEE_ID, RECEIVED_QUANTITY,
                           DIFFERENCE_QUANTITY, DIFFERENCE_REASON, RECEIPT_STATUS, CREATED_AT)
VALUES (20,
        (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'store_time'),
        16,
        0,
        NULL,
        'RECEIVED',
        TO_DATE('2026-05-06 10:40:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO STORE_RECEIPT (ORDER_REQUEST_ID, CONFIRM_EMPLOYEE_ID, RECEIVED_QUANTITY,
                           DIFFERENCE_QUANTITY, DIFFERENCE_REASON, RECEIPT_STATUS, CREATED_AT)
VALUES (21,
        (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'store_system'),
        10,
        0,
        NULL,
        'RECEIVED',
        TO_DATE('2026-05-07 11:57:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO STORE_RECEIPT (ORDER_REQUEST_ID, CONFIRM_EMPLOYEE_ID, RECEIVED_QUANTITY,
                           DIFFERENCE_QUANTITY, DIFFERENCE_REASON, RECEIPT_STATUS, CREATED_AT)
VALUES (22,
        (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'store_cashmere'),
        6,
        0,
        NULL,
        'RECEIVED',
        TO_DATE('2026-05-07 12:14:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO STORE_RECEIPT (ORDER_REQUEST_ID, CONFIRM_EMPLOYEE_ID, RECEIVED_QUANTITY,
                           DIFFERENCE_QUANTITY, DIFFERENCE_REASON, RECEIPT_STATUS, CREATED_AT)
VALUES (23,
        (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'store_time'),
        8,
        4,
        '박스 파손으로 4개 미입고',
        'PARTIAL_RECEIVED',
        TO_DATE('2026-05-07 13:31:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO STORE_RECEIPT (ORDER_REQUEST_ID, CONFIRM_EMPLOYEE_ID, RECEIVED_QUANTITY,
                           DIFFERENCE_QUANTITY, DIFFERENCE_REASON, RECEIPT_STATUS, CREATED_AT)
VALUES (24,
        (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'store_system'),
        13,
        2,
        '검수 중 2개 불량 확인',
        'PARTIAL_RECEIVED',
        TO_DATE('2026-05-07 10:48:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO STORE_RECEIPT (ORDER_REQUEST_ID, CONFIRM_EMPLOYEE_ID, RECEIVED_QUANTITY,
                           DIFFERENCE_QUANTITY, DIFFERENCE_REASON, RECEIPT_STATUS, CREATED_AT)
VALUES (25,
        (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'store_mine'),
        7,
        2,
        '배송 누락 2개 발생',
        'PARTIAL_RECEIVED',
        TO_DATE('2026-05-08 11:05:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO STORE_RECEIPT (ORDER_REQUEST_ID, CONFIRM_EMPLOYEE_ID, RECEIVED_QUANTITY,
                           DIFFERENCE_QUANTITY, DIFFERENCE_REASON, RECEIPT_STATUS, CREATED_AT)
VALUES (26,
        (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'store_time'),
        0,
        5,
        '오배송으로 전량 입고 취소',
        'CANCELED',
        TO_DATE('2026-05-08 12:22:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO STORE_RECEIPT (ORDER_REQUEST_ID, CONFIRM_EMPLOYEE_ID, RECEIVED_QUANTITY,
                           DIFFERENCE_QUANTITY, DIFFERENCE_REASON, RECEIPT_STATUS, CREATED_AT)
VALUES (27,
        (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'store_mine'),
        0,
        4,
        '상품 하자로 전량 입고 취소',
        'CANCELED',
        TO_DATE('2026-05-08 13:39:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO STORE_RECEIPT (ORDER_REQUEST_ID, CONFIRM_EMPLOYEE_ID, RECEIVED_QUANTITY,
                           DIFFERENCE_QUANTITY, DIFFERENCE_REASON, RECEIPT_STATUS, CREATED_AT)
VALUES (28,
        (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE LOGIN_ID = 'store_cashmere'),
        0,
        7,
        '검수 불합격으로 전량 취소',
        'CANCELED',
        TO_DATE('2026-05-08 10:56:00', 'YYYY-MM-DD HH24:MI:SS'));

COMMIT;
