/* =========================================================
   HIMS Master Data INSERT - IDENTITY 대응 버전
   대상 테이블: ROLE, BRANCH, BRAND, CATEGORY, STORE, PRODUCT, EMPLOYEE
   기준: 현대백화점 물류재고 ERD 데이터 v1.3
   변경 반영:
   - PK 컬럼이 GENERATED BY DEFAULT AS IDENTITY로 변경되어 PK 컬럼은 INSERT에서 제외
   - FK 컬럼은 이름 기반 서브쿼리로 참조
   - CREATED_AT 기본값은 대부분 DEFAULT SYSDATE 사용
========================================================= */

/* =========================================================
   1. ROLE - 권한
========================================================= */
INSERT INTO ROLE (ROLE_NAME,
                  ROLE_DESCRIPTION)
VALUES ('관리자',
        '기준 정보 및 전체 현황 관리');

INSERT INTO ROLE (ROLE_NAME,
                  ROLE_DESCRIPTION)
VALUES ('발주처담당자',
        '발주 승인/반려 및 발주처 재고 관리');

INSERT INTO ROLE (ROLE_NAME,
                  ROLE_DESCRIPTION)
VALUES ('입점매장담당자',
        '입점매장 재고 조회 및 발주 요청/입고 확인');

INSERT INTO ROLE (ROLE_NAME,
                  ROLE_DESCRIPTION)
VALUES ('일반직원',
        '권한없음.');

/* =========================================================
   2. BRANCH - 지점
   Excel 운영상태 '운영' -> DDL CHECK 값 'ACTIVE'로 변환
========================================================= */
INSERT INTO BRANCH (BRANCH_NAME,
                    ADDRESS,
                    PHONE_NUMBER,
                    OPERATION_STATUS)
VALUES ('더현대서울',
        '서울특별시 영등포구 여의대로 108',
        '02-767-2233',
        'ACTIVE');

INSERT INTO BRANCH (BRANCH_NAME,
                    ADDRESS,
                    PHONE_NUMBER,
                    OPERATION_STATUS)
VALUES ('현대백화점 판교점',
        '경기도 성남시 분당구 판교역로146번길 20',
        '031-5170-2233',
        'ACTIVE');

INSERT INTO BRANCH (BRANCH_NAME,
                    ADDRESS,
                    PHONE_NUMBER,
                    OPERATION_STATUS)
VALUES ('현대백화점 무역센터점',
        '서울특별시 강남구 테헤란로 517',
        '02-552-2233',
        'ACTIVE');

/* =========================================================
   3. BRAND - 브랜드
   Excel 운영상태 '운영' -> DDL CHECK 값 'ACTIVE'로 변환
========================================================= */
INSERT INTO BRAND (BRAND_NAME,
                   MANAGER_NAME,
                   PHONE_NUMBER,
                   OPERATION_STATUS)
VALUES ('TIME',
        '김도윤',
        '02-3416-2000',
        'ACTIVE');

INSERT INTO BRAND (BRAND_NAME,
                   MANAGER_NAME,
                   PHONE_NUMBER,
                   OPERATION_STATUS)
VALUES ('SYSTEM',
        '박서연',
        '02-3416-2100',
        'ACTIVE');

INSERT INTO BRAND (BRAND_NAME,
                   MANAGER_NAME,
                   PHONE_NUMBER,
                   OPERATION_STATUS)
VALUES ('MINE',
        '이민재',
        '02-3416-2200',
        'ACTIVE');

INSERT INTO BRAND (BRAND_NAME,
                   MANAGER_NAME,
                   PHONE_NUMBER,
                   OPERATION_STATUS)
VALUES ('THE CASHMERE',
        '최유진',
        '02-3416-2300',
        'ACTIVE');

/* =========================================================
   4. CATEGORY - 카테고리
   상위 카테고리 FK 때문에 부모 카테고리부터 INSERT
========================================================= */
INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES (NULL,
        '의류',
        1,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '의류'),
        '여성의류',
        2,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '여성의류'),
        '여성아우터',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '여성의류'),
        '여성원피스',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '여성의류'),
        '여성니트/탑',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '여성의류'),
        '여성하의',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '의류'),
        '남성의류',
        2,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '남성의류'),
        '남성아우터',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '남성의류'),
        '남성니트/탑',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '남성의류'),
        '남성하의',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES (NULL,
        '가구',
        1,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '가구'),
        '거실가구',
        2,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '거실가구'),
        '소파',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '거실가구'),
        '테이블',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '가구'),
        '침실가구',
        2,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '침실가구'),
        '침대',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '침실가구'),
        '옷장',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '가구'),
        '주방가구',
        2,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '주방가구'),
        '식탁',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '주방가구'),
        '의자',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES (NULL,
        '생활용품',
        1,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '생활용품'),
        '주방용품',
        2,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '주방용품'),
        '식기류',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '주방용품'),
        '조리도구',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '생활용품'),
        '욕실용품',
        2,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '욕실용품'),
        '수건',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '욕실용품'),
        '욕실소품',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '생활용품'),
        '홈데코',
        2,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '홈데코'),
        '조명',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '홈데코'),
        '인테리어소품',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES (NULL,
        '잡화',
        1,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '잡화'),
        '가방',
        2,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '가방'),
        '여성가방',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '가방'),
        '남성가방',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '잡화'),
        '신발',
        2,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '신발'),
        '여성신발',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '신발'),
        '남성신발',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '잡화'),
        '액세서리',
        2,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '액세서리'),
        '주얼리',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '액세서리'),
        '스카프/머플러',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES (NULL,
        '식품',
        1,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '식품'),
        '신선식품',
        2,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '신선식품'),
        '과일',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '신선식품'),
        '정육',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '식품'),
        '가공식품',
        2,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '가공식품'),
        '간편식',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '가공식품'),
        '소스/조미료',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '식품'),
        '델리',
        2,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '델리'),
        '도시락',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '델리'),
        '샐러드',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES (NULL,
        '기타',
        1,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '기타'),
        '기타상품',
        2,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '기타상품'),
        '시즌기획상품',
        3,
        'Y');

INSERT INTO CATEGORY (PARENT_CATEGORY_ID,
                      CATEGORY_NAME,
                      CATEGORY_LEVEL,
                      IS_ACTIVE)
VALUES ((SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '기타상품'),
        '행사상품',
        3,
        'Y');

/* =========================================================
   5. STORE - 입점매장
   Excel 운영상태 '운영' -> DDL CHECK 값 'ACTIVE'로 변환
========================================================= */
INSERT INTO STORE (BRANCH_ID,
                   BRAND_ID,
                   STORE_NAME,
                   FLOOR_INFO,
                   STORE_LOCATION,
                   OPERATION_STATUS)
VALUES ((SELECT BRANCH_ID FROM BRANCH WHERE BRANCH_NAME = '더현대서울'),
        (SELECT BRAND_ID FROM BRAND WHERE BRAND_NAME = 'THE CASHMERE'),
        'THE CASHMERE 더현대서울점',
        '3F',
        '여성패션존 A-12',
        'ACTIVE');

INSERT INTO STORE (BRANCH_ID,
                   BRAND_ID,
                   STORE_NAME,
                   FLOOR_INFO,
                   STORE_LOCATION,
                   OPERATION_STATUS)
VALUES ((SELECT BRANCH_ID FROM BRANCH WHERE BRANCH_NAME = '현대백화점 판교점'),
        (SELECT BRAND_ID FROM BRAND WHERE BRAND_NAME = 'TIME'),
        'TIME 판교점',
        '2F',
        '여성패션존 B-04',
        'ACTIVE');

INSERT INTO STORE (BRANCH_ID,
                   BRAND_ID,
                   STORE_NAME,
                   FLOOR_INFO,
                   STORE_LOCATION,
                   OPERATION_STATUS)
VALUES ((SELECT BRANCH_ID FROM BRANCH WHERE BRANCH_NAME = '현대백화점 무역센터점'),
        (SELECT BRAND_ID FROM BRAND WHERE BRAND_NAME = 'SYSTEM'),
        'SYSTEM 무역센터점',
        '4F',
        '영캐주얼존 C-03',
        'ACTIVE');

INSERT INTO STORE (BRANCH_ID,
                   BRAND_ID,
                   STORE_NAME,
                   FLOOR_INFO,
                   STORE_LOCATION,
                   OPERATION_STATUS)
VALUES ((SELECT BRANCH_ID FROM BRANCH WHERE BRANCH_NAME = '더현대서울'),
        (SELECT BRAND_ID FROM BRAND WHERE BRAND_NAME = 'MINE'),
        'MINE 더현대서울점',
        '3F',
        '여성패션존 A-15',
        'ACTIVE');

/* =========================================================
   6. PRODUCT - 상품
   Excel 상품상태 '판매 가능' -> DDL CHECK 값 'ON_SALE'로 변환
========================================================= */
INSERT INTO PRODUCT (BRAND_ID,
                     CATEGORY_ID,
                     PRODUCT_NAME,
                     PRICE,
                     SEASON_TYPE,
                     PRODUCT_STATUS,
                     CREATED_AT)
VALUES ((SELECT BRAND_ID FROM BRAND WHERE BRAND_NAME = 'TIME'),
        (SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '여성아우터'),
        'TIME 울 블렌드 재킷',
        398000,
        '가을/겨울',
        'ON_SALE',
        TO_DATE('2026-02-10', 'YYYY-MM-DD'));

INSERT INTO PRODUCT (BRAND_ID,
                     CATEGORY_ID,
                     PRODUCT_NAME,
                     PRICE,
                     SEASON_TYPE,
                     PRODUCT_STATUS,
                     CREATED_AT)
VALUES ((SELECT BRAND_ID FROM BRAND WHERE BRAND_NAME = 'TIME'),
        (SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '여성원피스'),
        'TIME 썸머 린넨 원피스',
        268000,
        '봄/여름',
        'ON_SALE',
        TO_DATE('2026-03-05', 'YYYY-MM-DD'));

INSERT INTO PRODUCT (BRAND_ID,
                     CATEGORY_ID,
                     PRODUCT_NAME,
                     PRICE,
                     SEASON_TYPE,
                     PRODUCT_STATUS,
                     CREATED_AT)
VALUES ((SELECT BRAND_ID FROM BRAND WHERE BRAND_NAME = 'SYSTEM'),
        (SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '여성니트/탑'),
        'SYSTEM 캐시미어 니트',
        328000,
        '가을/겨울',
        'ON_SALE',
        TO_DATE('2026-02-18', 'YYYY-MM-DD'));

INSERT INTO PRODUCT (BRAND_ID,
                     CATEGORY_ID,
                     PRODUCT_NAME,
                     PRICE,
                     SEASON_TYPE,
                     PRODUCT_STATUS,
                     CREATED_AT)
VALUES ((SELECT BRAND_ID FROM BRAND WHERE BRAND_NAME = 'MINE'),
        (SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '여성아우터'),
        'MINE 트렌치 코트',
        528000,
        '봄/여름',
        'ON_SALE',
        TO_DATE('2026-03-12', 'YYYY-MM-DD'));

INSERT INTO PRODUCT (BRAND_ID,
                     CATEGORY_ID,
                     PRODUCT_NAME,
                     PRICE,
                     SEASON_TYPE,
                     PRODUCT_STATUS,
                     CREATED_AT)
VALUES ((SELECT BRAND_ID FROM BRAND WHERE BRAND_NAME = 'THE CASHMERE'),
        (SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = '여성니트/탑'),
        'THE CASHMERE 홀가먼트 니트',
        458000,
        '가을/겨울',
        'ON_SALE',
        TO_DATE('2026-02-25', 'YYYY-MM-DD'));

/* =========================================================
   7. EMPLOYEE - 직원
   주의:
   - Excel에는 발주처ID 컬럼이 있지만 현재 EMPLOYEE DDL에는 해당 컬럼이 없으므로 제외
   - STORE_ID가 없는 발주처담당자/관리자는 NULL 처리
========================================================= */
INSERT INTO EMPLOYEE (ROLE_ID,
                      STORE_ID,
                      LOGIN_ID,
                      PASSWORD,
                      EMPLOYEE_NAME,
                      PHONE_NUMBER,
                      IS_ACTIVE)
VALUES ((SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = '관리자'),
        NULL,
        'admin01',
        'pass1234',
        '정관리',
        '010-1000-0001',
        'Y');

INSERT INTO EMPLOYEE (ROLE_ID,
                      STORE_ID,
                      LOGIN_ID,
                      PASSWORD,
                      EMPLOYEE_NAME,
                      PHONE_NUMBER,
                      IS_ACTIVE)
VALUES ((SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = '발주처담당자'),
        NULL,
        'logi_time',
        'pass1234',
        '오물류',
        '010-1000-0002',
        'Y');

INSERT INTO EMPLOYEE (ROLE_ID,
                      STORE_ID,
                      LOGIN_ID,
                      PASSWORD,
                      EMPLOYEE_NAME,
                      PHONE_NUMBER,
                      IS_ACTIVE)
VALUES ((SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = '발주처담당자'),
        NULL,
        'logi_system',
        'pass1234',
        '문출고',
        '010-1000-0003',
        'Y');

INSERT INTO EMPLOYEE (ROLE_ID,
                      STORE_ID,
                      LOGIN_ID,
                      PASSWORD,
                      EMPLOYEE_NAME,
                      PHONE_NUMBER,
                      IS_ACTIVE)
VALUES ((SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = '발주처담당자'),
        NULL,
        'logi_mine',
        'pass1234',
        '최배송',
        '010-1000-0004',
        'Y');

INSERT INTO EMPLOYEE (ROLE_ID,
                      STORE_ID,
                      LOGIN_ID,
                      PASSWORD,
                      EMPLOYEE_NAME,
                      PHONE_NUMBER,
                      IS_ACTIVE)
VALUES ((SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = '발주처담당자'),
        NULL,
        'logi_cashmere',
        'pass1234',
        '서물류',
        '010-1000-0009',
        'Y');

INSERT INTO EMPLOYEE (ROLE_ID,
                      STORE_ID,
                      LOGIN_ID,
                      PASSWORD,
                      EMPLOYEE_NAME,
                      PHONE_NUMBER,
                      IS_ACTIVE)
VALUES ((SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = '입점매장담당자'),
        (SELECT STORE_ID FROM STORE WHERE STORE_NAME = 'THE CASHMERE 더현대서울점'),
        'store_cashmere',
        'pass1234',
        '김매장',
        '010-1000-0005',
        'Y');

INSERT INTO EMPLOYEE (ROLE_ID,
                      STORE_ID,
                      LOGIN_ID,
                      PASSWORD,
                      EMPLOYEE_NAME,
                      PHONE_NUMBER,
                      IS_ACTIVE)
VALUES ((SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = '입점매장담당자'),
        (SELECT STORE_ID FROM STORE WHERE STORE_NAME = 'TIME 판교점'),
        'store_time',
        'pass1234',
        '이담당',
        '010-1000-0006',
        'Y');

INSERT INTO EMPLOYEE (ROLE_ID,
                      STORE_ID,
                      LOGIN_ID,
                      PASSWORD,
                      EMPLOYEE_NAME,
                      PHONE_NUMBER,
                      IS_ACTIVE)
VALUES ((SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = '입점매장담당자'),
        (SELECT STORE_ID FROM STORE WHERE STORE_NAME = 'SYSTEM 무역센터점'),
        'store_system',
        'pass1234',
        '박담당',
        '010-1000-0007',
        'Y');

INSERT INTO EMPLOYEE (ROLE_ID,
                      STORE_ID,
                      LOGIN_ID,
                      PASSWORD,
                      EMPLOYEE_NAME,
                      PHONE_NUMBER,
                      IS_ACTIVE)
VALUES ((SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = '입점매장담당자'),
        (SELECT STORE_ID FROM STORE WHERE STORE_NAME = 'MINE 더현대서울점'),
        'store_mine',
        'pass1234',
        '한담당',
        '010-1000-0008',
        'Y');

COMMIT;
